[2014-07-14 01:41:16] log.ERROR: exception 'ErrorException' with message 'Undefined variable: file' in D:\zend\Apache2\htdocs\Ta_Web\app\controllers\PenerbitController.php:43 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\app\controllers\PenerbitController.php(43): Illuminate\Exception\Handler->handleError(8, 'Undefined varia...', 'D:\zend\Apache2...', 43, Array) #1 [internal function]: App\Controllers\PenerbitController->AddProses() #2 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array) #3 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('addProses', Array) #4 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4952): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'addProses', Array) #5 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #6 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8178): call_user_func_array(Object(Closure), Array) #7 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8165): Illuminate\Routing\Route->callCallable() #8 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4963): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #9 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #10 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #11 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #12 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #13 {main} [] []
[2014-07-14 01:43:07] log.ERROR: exception 'ErrorException' with message 'Undefined variable: lokasiDbFile' in D:\zend\Apache2\htdocs\Ta_Web\app\controllers\PenerbitController.php:49 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\app\controllers\PenerbitController.php(49): Illuminate\Exception\Handler->handleError(8, 'Undefined varia...', 'D:\zend\Apache2...', 49, Array) #1 [internal function]: App\Controllers\PenerbitController->AddProses() #2 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array) #3 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('addProses', Array) #4 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4952): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'addProses', Array) #5 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #6 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8178): call_user_func_array(Object(Closure), Array) #7 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8165): Illuminate\Routing\Route->callCallable() #8 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4963): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #9 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #10 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #11 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #12 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #13 {main} [] []
[2014-07-14 01:43:26] log.ERROR: exception 'ErrorException' with message 'Undefined variable: pathDb' in D:\zend\Apache2\htdocs\Ta_Web\app\controllers\PenerbitController.php:58 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\app\controllers\PenerbitController.php(58): Illuminate\Exception\Handler->handleError(8, 'Undefined varia...', 'D:\zend\Apache2...', 58, Array) #1 [internal function]: App\Controllers\PenerbitController->AddProses() #2 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array) #3 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('addProses', Array) #4 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4952): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'addProses', Array) #5 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #6 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8178): call_user_func_array(Object(Closure), Array) #7 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8165): Illuminate\Routing\Route->callCallable() #8 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4963): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #9 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #10 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #11 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #12 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #13 {main} [] []
[2014-07-14 03:04:13] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php:5129 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4974): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4962): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #5 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #6 {main} [] []
[2014-07-14 03:04:16] log.ERROR: exception 'ErrorException' with message 'unlink(D:\zend\Apache2\htdocs\Ta_Web\public/images/Koala.jpg): No such file or directory' in D:\zend\Apache2\htdocs\Ta_Web\app\controllers\PenerbitController.php:69 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleError(2, 'unlink(D:\zend\...', 'D:\zend\Apache2...', 69, Array) #1 D:\zend\Apache2\htdocs\Ta_Web\app\controllers\PenerbitController.php(69): unlink('D:\zend\Apache2...') #2 [internal function]: App\Controllers\PenerbitController->Delete('13') #3 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array) #4 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('delete', Array) #5 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4952): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'delete', Array) #6 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('13') #7 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8178): call_user_func_array(Object(Closure), Array) #8 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8165): Illuminate\Routing\Route->callCallable() #9 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4963): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #10 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #11 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #12 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #13 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #14 {main} [] []
[2014-07-14 03:05:23] log.ERROR: exception 'PDOException' with message 'SQLSTATE[HY000]: General error: 1364 Field 'sejarah' doesn't have a default value' in D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Connection.php:331 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Connection.php(331): PDOStatement->execute(Array) #1 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Connection.php(521): Illuminate\Database\Connection->Illuminate\Database\{closure}(Object(Illuminate\Database\MySqlConnection), 'insert into `pe...', Array) #2 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Connection.php(332): Illuminate\Database\Connection->run('insert into `pe...', Array, Object(Closure)) #3 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Connection.php(289): Illuminate\Database\Connection->statement('insert into `pe...', Array) #4 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Query\Processors\Processor.php(30): Illuminate\Database\Connection->insert('insert into `pe...', Array) #5 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1444): Illuminate\Database\Query\Processors\Processor->processInsertGetId(Object(Illuminate\Database\Query\Builder), 'insert into `pe...', Array, 'id') #6 [internal function]: Illuminate\Database\Query\Builder->insertGetId(Array, 'id') #7 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Builder.php(786): call_user_func_array(Array, Array) #8 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(5947): Illuminate\Database\Eloquent\Builder->__call('insertGetId', Array) #9 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(5947): Illuminate\Database\Eloquent\Builder->insertGetId(Array, 'id') #10 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(5937): Illuminate\Database\Eloquent\Model->insertAndSetId(Object(Illuminate\Database\Eloquent\Builder), Array) #11 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(5896): Illuminate\Database\Eloquent\Model->performInsert(Object(Illuminate\Database\Eloquent\Builder)) #12 D:\zend\Apache2\htdocs\Ta_Web\app\controllers\PenerbitController.php(57): Illuminate\Database\Eloquent\Model->save() #13 [internal function]: App\Controllers\PenerbitController->AddProses() #14 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array) #15 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('addProses', Array) #16 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4952): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'addProses', Array) #17 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #18 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8178): call_user_func_array(Object(Closure), Array) #19 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8165): Illuminate\Routing\Route->callCallable() #20 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4963): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #21 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #22 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #23 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #24 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #25 {main} Next exception 'Exception' with message 'SQLSTATE[HY000]: General error: 1364 Field 'sejarah' doesn't have a default value (SQL: insert into `penerbit` (`nama_penerbit`, `alamat`, `no_tlp`, `gambar`) values (?, ?, ?, ?)) (Bindings: array (   0 => 'dipa',   1 => 'jlan',   2 => 'asdfa',   3 => 'images/Desain Rumah Minimalis 00458b.jpg', ))' in D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Connection.php:556 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Connection.php(529): Illuminate\Database\Connection->handleQueryException(Object(PDOException), 'insert into `pe...', Array) #1 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Connection.php(332): Illuminate\Database\Connection->run('insert into `pe...', Array, Object(Closure)) #2 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Connection.php(289): Illuminate\Database\Connection->statement('insert into `pe...', Array) #3 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Query\Processors\Processor.php(30): Illuminate\Database\Connection->insert('insert into `pe...', Array) #4 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1444): Illuminate\Database\Query\Processors\Processor->processInsertGetId(Object(Illuminate\Database\Query\Builder), 'insert into `pe...', Array, 'id') #5 [internal function]: Illuminate\Database\Query\Builder->insertGetId(Array, 'id') #6 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Builder.php(786): call_user_func_array(Array, Array) #7 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(5947): Illuminate\Database\Eloquent\Builder->__call('insertGetId', Array) #8 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(5947): Illuminate\Database\Eloquent\Builder->insertGetId(Array, 'id') #9 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(5937): Illuminate\Database\Eloquent\Model->insertAndSetId(Object(Illuminate\Database\Eloquent\Builder), Array) #10 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(5896): Illuminate\Database\Eloquent\Model->performInsert(Object(Illuminate\Database\Eloquent\Builder)) #11 D:\zend\Apache2\htdocs\Ta_Web\app\controllers\PenerbitController.php(57): Illuminate\Database\Eloquent\Model->save() #12 [internal function]: App\Controllers\PenerbitController->AddProses() #13 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array) #14 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('addProses', Array) #15 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4952): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'addProses', Array) #16 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #17 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8178): call_user_func_array(Object(Closure), Array) #18 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8165): Illuminate\Routing\Route->callCallable() #19 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4963): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #20 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #21 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #22 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #23 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #24 {main} [] []
[2014-07-14 03:10:14] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php:5129 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4974): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4962): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #5 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #6 {main} [] []
[2014-07-14 03:10:16] log.ERROR: exception 'ErrorException' with message 'unlink(D:\zend\Apache2\htdocs\Ta_Web\public/images/Desain-Rumah-Minimalis-1-Lantai-Mewah.jpg): No such file or directory' in D:\zend\Apache2\htdocs\Ta_Web\app\controllers\PenerbitController.php:70 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleError(2, 'unlink(D:\zend\...', 'D:\zend\Apache2...', 70, Array) #1 D:\zend\Apache2\htdocs\Ta_Web\app\controllers\PenerbitController.php(70): unlink('D:\zend\Apache2...') #2 [internal function]: App\Controllers\PenerbitController->Delete('66') #3 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array) #4 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('delete', Array) #5 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4952): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'delete', Array) #6 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('66') #7 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8178): call_user_func_array(Object(Closure), Array) #8 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8165): Illuminate\Routing\Route->callCallable() #9 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4963): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #10 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #11 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #12 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #13 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #14 {main} [] []
[2014-07-14 03:11:24] log.ERROR: exception 'ErrorException' with message 'unlink(D:\zend\Apache2\htdocs\Ta_Web\public/images/Desain-Rumah-Minimalis-1-Lantai-Mewah.jpg): No such file or directory' in D:\zend\Apache2\htdocs\Ta_Web\app\controllers\PenerbitController.php:70 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleError(2, 'unlink(D:\zend\...', 'D:\zend\Apache2...', 70, Array) #1 D:\zend\Apache2\htdocs\Ta_Web\app\controllers\PenerbitController.php(70): unlink('D:\zend\Apache2...') #2 [internal function]: App\Controllers\PenerbitController->Delete('66') #3 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array) #4 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('delete', Array) #5 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4952): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'delete', Array) #6 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('66') #7 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8178): call_user_func_array(Object(Closure), Array) #8 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8165): Illuminate\Routing\Route->callCallable() #9 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4963): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #10 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #11 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #12 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #13 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #14 {main} [] []
[2014-07-14 03:11:27] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php:5129 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4974): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4962): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #5 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #6 {main} [] []
[2014-07-14 03:11:29] log.ERROR: exception 'ErrorException' with message 'unlink(D:\zend\Apache2\htdocs\Ta_Web\public/images/Desain-Rumah-Minimalis-1-Lantai-Mewah.jpg): No such file or directory' in D:\zend\Apache2\htdocs\Ta_Web\app\controllers\PenerbitController.php:70 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleError(2, 'unlink(D:\zend\...', 'D:\zend\Apache2...', 70, Array) #1 D:\zend\Apache2\htdocs\Ta_Web\app\controllers\PenerbitController.php(70): unlink('D:\zend\Apache2...') #2 [internal function]: App\Controllers\PenerbitController->Delete('66') #3 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array) #4 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('delete', Array) #5 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4952): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'delete', Array) #6 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('66') #7 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8178): call_user_func_array(Object(Closure), Array) #8 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8165): Illuminate\Routing\Route->callCallable() #9 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4963): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #10 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #11 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #12 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #13 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #14 {main} [] []
[2014-07-14 03:12:17] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php:5129 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4974): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4962): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #5 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #6 {main} [] []
[2014-07-14 03:12:45] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php:5129 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4974): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4962): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #5 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #6 {main} [] []
[2014-07-14 03:12:45] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php:5129 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4974): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4962): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #5 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #6 {main} [] []
[2014-07-14 03:14:03] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php:5129 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4974): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4962): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #5 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #6 {main} [] []
[2014-07-14 03:14:03] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php:5129 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4974): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4962): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #5 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #6 {main} [] []
[2014-07-14 03:14:03] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php:5129 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4974): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4962): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #5 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #6 {main} [] []
[2014-07-14 03:21:52] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php:5129 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4974): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4962): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #5 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #6 {main} [] []
[2014-07-14 03:21:53] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php:5129 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4974): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4962): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #5 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #6 {main} [] []
[2014-07-14 03:21:53] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php:5129 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4974): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4962): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #5 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #6 {main} [] []
[2014-07-14 03:21:55] log.ERROR: exception 'ErrorException' with message 'unlink(D:\zend\Apache2\htdocs\Ta_Web\public/images/Lambang_Kabupaten_Lombok_Timur.jpeg): No such file or directory' in D:\zend\Apache2\htdocs\Ta_Web\app\controllers\PenerbitController.php:71 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleError(2, 'unlink(D:\zend\...', 'D:\zend\Apache2...', 71, Array) #1 D:\zend\Apache2\htdocs\Ta_Web\app\controllers\PenerbitController.php(71): unlink('D:\zend\Apache2...') #2 [internal function]: App\Controllers\PenerbitController->Delete('68') #3 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array) #4 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('delete', Array) #5 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4952): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'delete', Array) #6 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('68') #7 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8178): call_user_func_array(Object(Closure), Array) #8 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8165): Illuminate\Routing\Route->callCallable() #9 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4963): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #10 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #11 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #12 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #13 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #14 {main} [] []
[2014-07-14 03:23:27] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php:5129 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4974): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4962): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #5 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #6 {main} [] []
[2014-07-14 03:23:28] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php:5129 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4974): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4962): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #5 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #6 {main} [] []
[2014-07-14 03:23:30] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php:5129 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4974): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4962): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #5 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #6 {main} [] []
[2014-07-14 03:25:12] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php:5129 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4974): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4962): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #5 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #6 {main} [] []
[2014-07-14 03:27:18] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php:5129 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4974): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4962): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #5 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #6 {main} [] []
[2014-07-14 03:27:56] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php:5129 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4974): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4962): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #5 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #6 {main} [] []
[2014-07-14 03:28:54] log.ERROR: exception 'ErrorException' with message 'unlink(D:\zend\Apache2\htdocs\Ta_Web\public/images/Desain-Rumah-Minimalis-1-Lantai-Mewah.jpg): No such file or directory' in D:\zend\Apache2\htdocs\Ta_Web\app\controllers\PenerbitController.php:72 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleError(2, 'unlink(D:\zend\...', 'D:\zend\Apache2...', 72, Array) #1 D:\zend\Apache2\htdocs\Ta_Web\app\controllers\PenerbitController.php(72): unlink('D:\zend\Apache2...') #2 [internal function]: App\Controllers\PenerbitController->Delete('72') #3 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array) #4 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('delete', Array) #5 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4952): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'delete', Array) #6 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('72') #7 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8178): call_user_func_array(Object(Closure), Array) #8 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8165): Illuminate\Routing\Route->callCallable() #9 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4963): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #10 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #11 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #12 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #13 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #14 {main} [] []
[2014-07-14 03:29:32] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php:5129 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4974): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4962): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #5 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #6 {main} [] []
[2014-07-14 04:05:20] log.ERROR: exception 'ErrorException' with message 'Trying to get property of non-object' in D:\zend\Apache2\htdocs\Ta_Web\app\storage\views\6cea172e687435ef61a499f5613826d3:11 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\app\storage\views\6cea172e687435ef61a499f5613826d3(11): Illuminate\Exception\Handler->handleError(8, 'Trying to get p...', 'D:\zend\Apache2...', 11, Array) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(9428): include('D:\zend\Apache2...') #2 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\View\Engines\CompilerEngine.php(45): Illuminate\View\Engines\PhpEngine->evaluatePath('D:\zend\Apache2...', Array) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(9314): Illuminate\View\Engines\CompilerEngine->get('D:\zend\Apache2...', Array) #4 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(9305): Illuminate\View\View->getContents() #5 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(9917): Illuminate\View\View->render() #6 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(9454): Illuminate\Http\Response->setContent(Object(Illuminate\View\View)) #7 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(5122): Symfony\Component\HttpFoundation\Response->__construct(Object(Illuminate\View\View)) #8 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(156): Illuminate\Routing\Router->prepare(Object(Illuminate\View\View), Object(Illuminate\Http\Request)) #9 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(126): Illuminate\Routing\Controllers\Controller->processResponse(Object(Illuminate\Routing\Router), 'Edit', Object(Illuminate\View\View)) #10 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4952): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'Edit', Array) #11 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('74') #12 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8178): call_user_func_array(Object(Closure), Array) #13 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8165): Illuminate\Routing\Route->callCallable() #14 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4963): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #15 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #16 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #17 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #18 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #19 {main} [] []
[2014-07-14 04:15:56] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php:5129 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4974): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4962): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #5 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #6 {main} [] []
[2014-07-14 05:45:58] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php:5129 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4974): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4962): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #5 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #6 {main} [] []
[2014-07-14 06:29:50] log.ERROR: exception 'ReflectionException' with message 'Class App\Controllers\Penerbitcotrolle1 does not exist' in D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php:169 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(169): ReflectionClass->__construct('App\Controllers...') #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(146): Illuminate\Container\Container->build('App\Controllers...', Array) #2 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(493): Illuminate\Container\Container->make('App\Controllers...', Array) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4951): Illuminate\Foundation\Application->make('App\Controllers...') #4 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #5 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8178): call_user_func_array(Object(Closure), Array) #6 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8165): Illuminate\Routing\Route->callCallable() #7 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4963): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #8 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #9 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #10 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #11 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #12 {main} [] []
[2014-07-14 06:30:57] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'App\Controllers\View' not found' in D:\zend\Apache2\htdocs\Ta_Web\app\controllers\PenerbitControlle1.php:13 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2014-07-14 06:31:46] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'App\Controllers\View' not found' in D:\zend\Apache2\htdocs\Ta_Web\app\controllers\PenerbitControlle1.php:13 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2014-07-14 06:31:58] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'App\Controllers\View' not found' in D:\zend\Apache2\htdocs\Ta_Web\app\controllers\PenerbitControlle1.php:13 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2014-07-14 06:32:39] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'App\Controllers\View' not found' in D:\zend\Apache2\htdocs\Ta_Web\app\controllers\PenerbitControlle1.php:13 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2014-07-14 06:33:54] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to undefined method Illuminate\View\View::make()' in D:\zend\Apache2\htdocs\Ta_Web\app\controllers\PenerbitControlle1.php:14 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2014-07-14 06:35:44] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to undefined method Illuminate\View\View::make()' in D:\zend\Apache2\htdocs\Ta_Web\app\controllers\PenerbitControlle1.php:15 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2014-07-14 06:35:54] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to undefined method Illuminate\View\View::make()' in D:\zend\Apache2\htdocs\Ta_Web\app\controllers\PenerbitControlle1.php:15 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2014-07-14 06:47:33] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to undefined method Illuminate\Database\Eloquent\Collection::links()' in D:\zend\Apache2\htdocs\Ta_Web\app\storage\views\eecbfdfc468020169e683f00580865e1:86 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2014-07-14 06:48:37] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to undefined method Illuminate\Database\Eloquent\Collection::links()' in D:\zend\Apache2\htdocs\Ta_Web\app\storage\views\eecbfdfc468020169e683f00580865e1:86 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2014-07-14 06:48:37] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to undefined method Illuminate\Database\Eloquent\Collection::links()' in D:\zend\Apache2\htdocs\Ta_Web\app\storage\views\eecbfdfc468020169e683f00580865e1:86 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2014-07-14 06:50:33] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to undefined method Illuminate\Database\Eloquent\Collection::links()' in D:\zend\Apache2\htdocs\Ta_Web\app\storage\views\eecbfdfc468020169e683f00580865e1:86 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2014-07-14 06:59:23] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php:5129 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4974): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4962): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #5 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #6 {main} [] []
[2014-07-14 07:00:20] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php:5129 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4974): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4962): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #5 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #6 {main} [] []
[2014-07-14 07:00:21] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php:5129 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4974): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4962): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #5 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #6 {main} [] []
[2014-07-14 07:01:42] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php:5129 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4974): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4962): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #5 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #6 {main} [] []
[2014-07-14 07:07:37] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'App\Controllers\Validator' not found' in D:\zend\Apache2\htdocs\Ta_Web\app\controllers\PenerbitControlle1.php:31 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2014-07-14 07:08:25] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to undefined method Illuminate\Validation\Validator::make()' in D:\zend\Apache2\htdocs\Ta_Web\app\controllers\PenerbitControlle1.php:33 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2014-07-14 07:09:18] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to undefined method Illuminate\Validation\Validator::make()' in D:\zend\Apache2\htdocs\Ta_Web\app\controllers\PenerbitControlle1.php:33 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2014-07-14 07:10:23] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to undefined method Illuminate\Validation\Validator::make()' in D:\zend\Apache2\htdocs\Ta_Web\app\controllers\PenerbitControlle1.php:34 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2014-07-14 07:10:53] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'App\Controllers\Input' not found' in D:\zend\Apache2\htdocs\Ta_Web\app\controllers\PenerbitControlle1.php:32 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2014-07-14 07:11:52] log.ERROR: exception 'ErrorException' with message 'Undefined variable: rules' in D:\zend\Apache2\htdocs\Ta_Web\app\controllers\PenerbitControlle1.php:33 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\app\controllers\PenerbitControlle1.php(33): Illuminate\Exception\Handler->handleError(8, 'Undefined varia...', 'D:\zend\Apache2...', 33, Array) #1 [internal function]: App\Controllers\PenerbitControlle1->AddProses() #2 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array) #3 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('addProses', Array) #4 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4952): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'addProses', Array) #5 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #6 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8178): call_user_func_array(Object(Closure), Array) #7 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8165): Illuminate\Routing\Route->callCallable() #8 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4963): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #9 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #10 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #11 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #12 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #13 {main} [] []
[2014-07-14 07:12:22] log.ERROR: exception 'ErrorException' with message 'Use of undefined constant Input - assumed 'Input'' in D:\zend\Apache2\htdocs\Ta_Web\app\controllers\PenerbitControlle1.php:35 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\app\controllers\PenerbitControlle1.php(35): Illuminate\Exception\Handler->handleError(8, 'Use of undefine...', 'D:\zend\Apache2...', 35, Array) #1 [internal function]: App\Controllers\PenerbitControlle1->AddProses() #2 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array) #3 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('addProses', Array) #4 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4952): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'addProses', Array) #5 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #6 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8178): call_user_func_array(Object(Closure), Array) #7 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8165): Illuminate\Routing\Route->callCallable() #8 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4963): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #9 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #10 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #11 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #12 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #13 {main} [] []
[2014-07-14 07:12:47] log.ERROR: exception 'ErrorException' with message 'Undefined variable: rules' in D:\zend\Apache2\htdocs\Ta_Web\app\controllers\PenerbitControlle1.php:33 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\app\controllers\PenerbitControlle1.php(33): Illuminate\Exception\Handler->handleError(8, 'Undefined varia...', 'D:\zend\Apache2...', 33, Array) #1 [internal function]: App\Controllers\PenerbitControlle1->AddProses() #2 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array) #3 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('addProses', Array) #4 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4952): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'addProses', Array) #5 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #6 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8178): call_user_func_array(Object(Closure), Array) #7 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8165): Illuminate\Routing\Route->callCallable() #8 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4963): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #9 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #10 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #11 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #12 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #13 {main} [] []
[2014-07-14 07:12:59] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'App\Controllers\Redirect' not found' in D:\zend\Apache2\htdocs\Ta_Web\app\controllers\PenerbitControlle1.php:37 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2014-07-14 07:15:18] log.ERROR: exception 'Exception' with message 'Serialization of 'Closure' is not allowed' in D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php:2297 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(2297): session_write_close() #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(2165): Symfony\Component\HttpFoundation\Session\Storage\NativeSessionStorage->save() #2 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(6701): Symfony\Component\HttpFoundation\Session\Session->save() #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4480): Illuminate\Session\Store->save() #4 [internal function]: Illuminate\Session\SessionServiceProvider->Illuminate\Session\{closure}(Object(Illuminate\Http\Request), Object(Illuminate\Http\RedirectResponse)) #5 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(5081): call_user_func_array(Object(Closure), Array) #6 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(5071): Illuminate\Routing\Router->callGlobalFilter(Object(Illuminate\Http\Request), 'close', Array) #7 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(522): Illuminate\Routing\Router->callCloseFilter(Object(Illuminate\Http\Request), Object(Illuminate\Http\RedirectResponse)) #8 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #9 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #10 {main} [] []
[2014-07-14 07:15:49] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Allowed memory size of 134217728 bytes exhausted (tried to allocate 127664128 bytes)' in D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Exception\resources\pretty-template.php:128 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2014-07-14 13:17:07] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php:5129 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4974): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4962): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #5 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #6 {main} [] []
[2014-07-14 13:17:28] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php:5129 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4974): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4962): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #5 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #6 {main} [] []
[2014-07-14 13:17:58] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php:5129 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4974): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4962): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #5 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #6 {main} [] []
[2014-07-14 13:35:04] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php:5129 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4974): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4962): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #5 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #6 {main} [] []
[2014-07-14 13:43:19] log.ERROR: exception 'PDOException' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'nama' in 'field list'' in D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Connection.php:331 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Connection.php(331): PDO->prepare('insert into `pe...') #1 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Connection.php(521): Illuminate\Database\Connection->Illuminate\Database\{closure}(Object(Illuminate\Database\MySqlConnection), 'insert into `pe...', Array) #2 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Connection.php(332): Illuminate\Database\Connection->run('insert into `pe...', Array, Object(Closure)) #3 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Connection.php(289): Illuminate\Database\Connection->statement('insert into `pe...', Array) #4 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Query\Processors\Processor.php(30): Illuminate\Database\Connection->insert('insert into `pe...', Array) #5 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1444): Illuminate\Database\Query\Processors\Processor->processInsertGetId(Object(Illuminate\Database\Query\Builder), 'insert into `pe...', Array, 'id') #6 [internal function]: Illuminate\Database\Query\Builder->insertGetId(Array, 'id') #7 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Builder.php(786): call_user_func_array(Array, Array) #8 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(5947): Illuminate\Database\Eloquent\Builder->__call('insertGetId', Array) #9 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(5947): Illuminate\Database\Eloquent\Builder->insertGetId(Array, 'id') #10 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(5937): Illuminate\Database\Eloquent\Model->insertAndSetId(Object(Illuminate\Database\Eloquent\Builder), Array) #11 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(5896): Illuminate\Database\Eloquent\Model->performInsert(Object(Illuminate\Database\Eloquent\Builder)) #12 D:\zend\Apache2\htdocs\Ta_Web\app\controllers\PenerbitController.php(53): Illuminate\Database\Eloquent\Model->save() #13 [internal function]: App\Controllers\PenerbitController->AddProses() #14 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array) #15 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('addProses', Array) #16 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4952): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'addProses', Array) #17 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #18 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8178): call_user_func_array(Object(Closure), Array) #19 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8165): Illuminate\Routing\Route->callCallable() #20 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4963): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #21 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #22 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #23 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #24 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #25 {main} Next exception 'Exception' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'nama' in 'field list' (SQL: insert into `penerbit` (`nama`, `gambar`) values (?, ?)) (Bindings: array (   0 => 'dipa',   1 => 'Public/images', ))' in D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Connection.php:556 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Connection.php(529): Illuminate\Database\Connection->handleQueryException(Object(PDOException), 'insert into `pe...', Array) #1 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Connection.php(332): Illuminate\Database\Connection->run('insert into `pe...', Array, Object(Closure)) #2 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Connection.php(289): Illuminate\Database\Connection->statement('insert into `pe...', Array) #3 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Query\Processors\Processor.php(30): Illuminate\Database\Connection->insert('insert into `pe...', Array) #4 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1444): Illuminate\Database\Query\Processors\Processor->processInsertGetId(Object(Illuminate\Database\Query\Builder), 'insert into `pe...', Array, 'id') #5 [internal function]: Illuminate\Database\Query\Builder->insertGetId(Array, 'id') #6 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Builder.php(786): call_user_func_array(Array, Array) #7 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(5947): Illuminate\Database\Eloquent\Builder->__call('insertGetId', Array) #8 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(5947): Illuminate\Database\Eloquent\Builder->insertGetId(Array, 'id') #9 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(5937): Illuminate\Database\Eloquent\Model->insertAndSetId(Object(Illuminate\Database\Eloquent\Builder), Array) #10 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(5896): Illuminate\Database\Eloquent\Model->performInsert(Object(Illuminate\Database\Eloquent\Builder)) #11 D:\zend\Apache2\htdocs\Ta_Web\app\controllers\PenerbitController.php(53): Illuminate\Database\Eloquent\Model->save() #12 [internal function]: App\Controllers\PenerbitController->AddProses() #13 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array) #14 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('addProses', Array) #15 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4952): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'addProses', Array) #16 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #17 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8178): call_user_func_array(Object(Closure), Array) #18 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8165): Illuminate\Routing\Route->callCallable() #19 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4963): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #20 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #21 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #22 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #23 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #24 {main} [] []
[2014-07-14 13:43:37] log.ERROR: exception 'PDOException' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'nama' in 'field list'' in D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Connection.php:331 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Connection.php(331): PDO->prepare('insert into `pe...') #1 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Connection.php(521): Illuminate\Database\Connection->Illuminate\Database\{closure}(Object(Illuminate\Database\MySqlConnection), 'insert into `pe...', Array) #2 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Connection.php(332): Illuminate\Database\Connection->run('insert into `pe...', Array, Object(Closure)) #3 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Connection.php(289): Illuminate\Database\Connection->statement('insert into `pe...', Array) #4 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Query\Processors\Processor.php(30): Illuminate\Database\Connection->insert('insert into `pe...', Array) #5 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1444): Illuminate\Database\Query\Processors\Processor->processInsertGetId(Object(Illuminate\Database\Query\Builder), 'insert into `pe...', Array, 'id') #6 [internal function]: Illuminate\Database\Query\Builder->insertGetId(Array, 'id') #7 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Builder.php(786): call_user_func_array(Array, Array) #8 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(5947): Illuminate\Database\Eloquent\Builder->__call('insertGetId', Array) #9 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(5947): Illuminate\Database\Eloquent\Builder->insertGetId(Array, 'id') #10 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(5937): Illuminate\Database\Eloquent\Model->insertAndSetId(Object(Illuminate\Database\Eloquent\Builder), Array) #11 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(5896): Illuminate\Database\Eloquent\Model->performInsert(Object(Illuminate\Database\Eloquent\Builder)) #12 D:\zend\Apache2\htdocs\Ta_Web\app\controllers\PenerbitController.php(53): Illuminate\Database\Eloquent\Model->save() #13 [internal function]: App\Controllers\PenerbitController->AddProses() #14 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array) #15 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('addProses', Array) #16 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4952): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'addProses', Array) #17 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #18 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8178): call_user_func_array(Object(Closure), Array) #19 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8165): Illuminate\Routing\Route->callCallable() #20 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4963): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #21 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #22 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #23 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #24 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #25 {main} Next exception 'Exception' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'nama' in 'field list' (SQL: insert into `penerbit` (`nama`, `gambar`) values (?, ?)) (Bindings: array (   0 => 'dipa',   1 => 'Public/images', ))' in D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Connection.php:556 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Connection.php(529): Illuminate\Database\Connection->handleQueryException(Object(PDOException), 'insert into `pe...', Array) #1 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Connection.php(332): Illuminate\Database\Connection->run('insert into `pe...', Array, Object(Closure)) #2 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Connection.php(289): Illuminate\Database\Connection->statement('insert into `pe...', Array) #3 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Query\Processors\Processor.php(30): Illuminate\Database\Connection->insert('insert into `pe...', Array) #4 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1444): Illuminate\Database\Query\Processors\Processor->processInsertGetId(Object(Illuminate\Database\Query\Builder), 'insert into `pe...', Array, 'id') #5 [internal function]: Illuminate\Database\Query\Builder->insertGetId(Array, 'id') #6 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Builder.php(786): call_user_func_array(Array, Array) #7 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(5947): Illuminate\Database\Eloquent\Builder->__call('insertGetId', Array) #8 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(5947): Illuminate\Database\Eloquent\Builder->insertGetId(Array, 'id') #9 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(5937): Illuminate\Database\Eloquent\Model->insertAndSetId(Object(Illuminate\Database\Eloquent\Builder), Array) #10 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(5896): Illuminate\Database\Eloquent\Model->performInsert(Object(Illuminate\Database\Eloquent\Builder)) #11 D:\zend\Apache2\htdocs\Ta_Web\app\controllers\PenerbitController.php(53): Illuminate\Database\Eloquent\Model->save() #12 [internal function]: App\Controllers\PenerbitController->AddProses() #13 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array) #14 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('addProses', Array) #15 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4952): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'addProses', Array) #16 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #17 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8178): call_user_func_array(Object(Closure), Array) #18 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8165): Illuminate\Routing\Route->callCallable() #19 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4963): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #20 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #21 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #22 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #23 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #24 {main} [] []
[2014-07-14 13:43:57] log.ERROR: exception 'PDOException' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'nama' in 'field list'' in D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Connection.php:331 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Connection.php(331): PDO->prepare('insert into `pe...') #1 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Connection.php(521): Illuminate\Database\Connection->Illuminate\Database\{closure}(Object(Illuminate\Database\MySqlConnection), 'insert into `pe...', Array) #2 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Connection.php(332): Illuminate\Database\Connection->run('insert into `pe...', Array, Object(Closure)) #3 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Connection.php(289): Illuminate\Database\Connection->statement('insert into `pe...', Array) #4 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Query\Processors\Processor.php(30): Illuminate\Database\Connection->insert('insert into `pe...', Array) #5 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1444): Illuminate\Database\Query\Processors\Processor->processInsertGetId(Object(Illuminate\Database\Query\Builder), 'insert into `pe...', Array, 'id') #6 [internal function]: Illuminate\Database\Query\Builder->insertGetId(Array, 'id') #7 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Builder.php(786): call_user_func_array(Array, Array) #8 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(5947): Illuminate\Database\Eloquent\Builder->__call('insertGetId', Array) #9 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(5947): Illuminate\Database\Eloquent\Builder->insertGetId(Array, 'id') #10 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(5937): Illuminate\Database\Eloquent\Model->insertAndSetId(Object(Illuminate\Database\Eloquent\Builder), Array) #11 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(5896): Illuminate\Database\Eloquent\Model->performInsert(Object(Illuminate\Database\Eloquent\Builder)) #12 D:\zend\Apache2\htdocs\Ta_Web\app\controllers\PenerbitController.php(53): Illuminate\Database\Eloquent\Model->save() #13 [internal function]: App\Controllers\PenerbitController->AddProses() #14 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array) #15 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('addProses', Array) #16 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4952): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'addProses', Array) #17 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #18 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8178): call_user_func_array(Object(Closure), Array) #19 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8165): Illuminate\Routing\Route->callCallable() #20 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4963): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #21 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #22 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #23 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #24 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #25 {main} Next exception 'Exception' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'nama' in 'field list' (SQL: insert into `penerbit` (`nama`, `gambar`) values (?, ?)) (Bindings: array (   0 => 'asd',   1 => 'Public/images', ))' in D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Connection.php:556 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Connection.php(529): Illuminate\Database\Connection->handleQueryException(Object(PDOException), 'insert into `pe...', Array) #1 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Connection.php(332): Illuminate\Database\Connection->run('insert into `pe...', Array, Object(Closure)) #2 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Connection.php(289): Illuminate\Database\Connection->statement('insert into `pe...', Array) #3 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Query\Processors\Processor.php(30): Illuminate\Database\Connection->insert('insert into `pe...', Array) #4 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1444): Illuminate\Database\Query\Processors\Processor->processInsertGetId(Object(Illuminate\Database\Query\Builder), 'insert into `pe...', Array, 'id') #5 [internal function]: Illuminate\Database\Query\Builder->insertGetId(Array, 'id') #6 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Builder.php(786): call_user_func_array(Array, Array) #7 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(5947): Illuminate\Database\Eloquent\Builder->__call('insertGetId', Array) #8 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(5947): Illuminate\Database\Eloquent\Builder->insertGetId(Array, 'id') #9 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(5937): Illuminate\Database\Eloquent\Model->insertAndSetId(Object(Illuminate\Database\Eloquent\Builder), Array) #10 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(5896): Illuminate\Database\Eloquent\Model->performInsert(Object(Illuminate\Database\Eloquent\Builder)) #11 D:\zend\Apache2\htdocs\Ta_Web\app\controllers\PenerbitController.php(53): Illuminate\Database\Eloquent\Model->save() #12 [internal function]: App\Controllers\PenerbitController->AddProses() #13 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array) #14 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('addProses', Array) #15 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4952): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'addProses', Array) #16 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #17 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8178): call_user_func_array(Object(Closure), Array) #18 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8165): Illuminate\Routing\Route->callCallable() #19 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4963): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #20 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #21 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #22 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #23 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #24 {main} [] []
[2014-07-14 13:44:09] log.ERROR: exception 'PDOException' with message 'SQLSTATE[HY000]: General error: 1364 Field 'sejarah' doesn't have a default value' in D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Connection.php:331 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Connection.php(331): PDOStatement->execute(Array) #1 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Connection.php(521): Illuminate\Database\Connection->Illuminate\Database\{closure}(Object(Illuminate\Database\MySqlConnection), 'insert into `pe...', Array) #2 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Connection.php(332): Illuminate\Database\Connection->run('insert into `pe...', Array, Object(Closure)) #3 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Connection.php(289): Illuminate\Database\Connection->statement('insert into `pe...', Array) #4 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Query\Processors\Processor.php(30): Illuminate\Database\Connection->insert('insert into `pe...', Array) #5 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1444): Illuminate\Database\Query\Processors\Processor->processInsertGetId(Object(Illuminate\Database\Query\Builder), 'insert into `pe...', Array, 'id') #6 [internal function]: Illuminate\Database\Query\Builder->insertGetId(Array, 'id') #7 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Builder.php(786): call_user_func_array(Array, Array) #8 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(5947): Illuminate\Database\Eloquent\Builder->__call('insertGetId', Array) #9 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(5947): Illuminate\Database\Eloquent\Builder->insertGetId(Array, 'id') #10 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(5937): Illuminate\Database\Eloquent\Model->insertAndSetId(Object(Illuminate\Database\Eloquent\Builder), Array) #11 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(5896): Illuminate\Database\Eloquent\Model->performInsert(Object(Illuminate\Database\Eloquent\Builder)) #12 D:\zend\Apache2\htdocs\Ta_Web\app\controllers\PenerbitController.php(53): Illuminate\Database\Eloquent\Model->save() #13 [internal function]: App\Controllers\PenerbitController->AddProses() #14 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array) #15 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('addProses', Array) #16 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4952): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'addProses', Array) #17 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #18 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8178): call_user_func_array(Object(Closure), Array) #19 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8165): Illuminate\Routing\Route->callCallable() #20 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4963): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #21 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #22 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #23 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #24 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #25 {main} Next exception 'Exception' with message 'SQLSTATE[HY000]: General error: 1364 Field 'sejarah' doesn't have a default value (SQL: insert into `penerbit` (`nama_penerbit`, `gambar`) values (?, ?)) (Bindings: array (   0 => 'asd',   1 => 'Public/images', ))' in D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Connection.php:556 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Connection.php(529): Illuminate\Database\Connection->handleQueryException(Object(PDOException), 'insert into `pe...', Array) #1 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Connection.php(332): Illuminate\Database\Connection->run('insert into `pe...', Array, Object(Closure)) #2 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Connection.php(289): Illuminate\Database\Connection->statement('insert into `pe...', Array) #3 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Query\Processors\Processor.php(30): Illuminate\Database\Connection->insert('insert into `pe...', Array) #4 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1444): Illuminate\Database\Query\Processors\Processor->processInsertGetId(Object(Illuminate\Database\Query\Builder), 'insert into `pe...', Array, 'id') #5 [internal function]: Illuminate\Database\Query\Builder->insertGetId(Array, 'id') #6 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Builder.php(786): call_user_func_array(Array, Array) #7 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(5947): Illuminate\Database\Eloquent\Builder->__call('insertGetId', Array) #8 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(5947): Illuminate\Database\Eloquent\Builder->insertGetId(Array, 'id') #9 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(5937): Illuminate\Database\Eloquent\Model->insertAndSetId(Object(Illuminate\Database\Eloquent\Builder), Array) #10 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(5896): Illuminate\Database\Eloquent\Model->performInsert(Object(Illuminate\Database\Eloquent\Builder)) #11 D:\zend\Apache2\htdocs\Ta_Web\app\controllers\PenerbitController.php(53): Illuminate\Database\Eloquent\Model->save() #12 [internal function]: App\Controllers\PenerbitController->AddProses() #13 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array) #14 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('addProses', Array) #15 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4952): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'addProses', Array) #16 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #17 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8178): call_user_func_array(Object(Closure), Array) #18 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8165): Illuminate\Routing\Route->callCallable() #19 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4963): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #20 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #21 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #22 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #23 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #24 {main} [] []
[2014-07-14 13:45:33] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php:5129 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4974): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4962): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #5 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #6 {main} [] []
[2014-07-14 13:45:42] log.ERROR: exception 'ErrorException' with message 'unlink(D:\zend\Apache2\htdocs\Ta_Web\public/Public/images): No such file or directory' in D:\zend\Apache2\htdocs\Ta_Web\app\controllers\PenerbitController.php:69 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleError(2, 'unlink(D:\zend\...', 'D:\zend\Apache2...', 69, Array) #1 D:\zend\Apache2\htdocs\Ta_Web\app\controllers\PenerbitController.php(69): unlink('D:\zend\Apache2...') #2 [internal function]: App\Controllers\PenerbitController->Delete('84') #3 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array) #4 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('delete', Array) #5 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4952): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'delete', Array) #6 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('84') #7 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8178): call_user_func_array(Object(Closure), Array) #8 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8165): Illuminate\Routing\Route->callCallable() #9 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4963): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #10 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #11 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #12 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #13 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #14 {main} [] []
[2014-07-14 13:47:15] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php:5129 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4974): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4962): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #5 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #6 {main} [] []
[2014-07-14 13:49:54] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php:5129 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4974): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4962): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #5 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #6 {main} [] []
[2014-07-14 13:57:36] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php:5129 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4974): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4962): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #5 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #6 {main} [] []
[2014-07-14 13:57:43] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php:5129 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4974): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4962): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #5 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #6 {main} [] []
[2014-07-14 13:57:43] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php:5129 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4974): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4962): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #5 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #6 {main} [] []
[2014-07-14 13:57:48] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php:5129 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4974): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4962): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #5 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #6 {main} [] []
[2014-07-14 13:57:48] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php:5129 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4974): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4962): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #5 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #6 {main} [] []
[2014-07-14 13:57:55] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php:5129 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4974): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4962): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #5 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #6 {main} [] []
[2014-07-14 13:57:55] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php:5129 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4974): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4962): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #5 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #6 {main} [] []
[2014-07-14 13:58:30] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php:5129 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4974): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4962): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #5 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #6 {main} [] []
[2014-07-14 13:58:32] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php:5129 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4974): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4962): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #5 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #6 {main} [] []
[2014-07-14 14:16:16] log.ERROR: exception 'ErrorException' with message 'Undefined property: Illuminate\Database\Eloquent\Collection::$id' in D:\zend\Apache2\htdocs\Ta_Web\app\controllers\PenerbitController.php:17 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\app\controllers\PenerbitController.php(17): Illuminate\Exception\Handler->handleError(8, 'Undefined prope...', 'D:\zend\Apache2...', 17, Array) #1 [internal function]: App\Controllers\PenerbitController->view() #2 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array) #3 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('view', Array) #4 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4952): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'view', Array) #5 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #6 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8178): call_user_func_array(Object(Closure), Array) #7 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8165): Illuminate\Routing\Route->callCallable() #8 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4963): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #9 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #10 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #11 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #12 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #13 {main} [] []
[2014-07-14 14:16:43] log.ERROR: exception 'ErrorException' with message 'Undefined property: Illuminate\Database\Eloquent\Collection::$nama_penerbit' in D:\zend\Apache2\htdocs\Ta_Web\app\controllers\PenerbitController.php:17 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\app\controllers\PenerbitController.php(17): Illuminate\Exception\Handler->handleError(8, 'Undefined prope...', 'D:\zend\Apache2...', 17, Array) #1 [internal function]: App\Controllers\PenerbitController->view() #2 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array) #3 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('view', Array) #4 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4952): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'view', Array) #5 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #6 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8178): call_user_func_array(Object(Closure), Array) #7 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8165): Illuminate\Routing\Route->callCallable() #8 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4963): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #9 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #10 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #11 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #12 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #13 {main} [] []
[2014-07-14 15:56:46] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php:5129 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4974): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4962): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #5 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #6 {main} [] []
[2014-07-14 16:00:54] log.ERROR: exception 'ErrorException' with message 'Undefined variable: data' in D:\zend\Apache2\htdocs\Ta_Web\app\controllers\PenerbitController.php:18 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\app\controllers\PenerbitController.php(18): Illuminate\Exception\Handler->handleError(8, 'Undefined varia...', 'D:\zend\Apache2...', 18, Array) #1 [internal function]: App\Controllers\PenerbitController->view() #2 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array) #3 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('view', Array) #4 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4952): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'view', Array) #5 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #6 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8178): call_user_func_array(Object(Closure), Array) #7 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8165): Illuminate\Routing\Route->callCallable() #8 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4963): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #9 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #10 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #11 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #12 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #13 {main} [] []
[2014-07-14 16:01:35] log.ERROR: exception 'ErrorException' with message 'Undefined variable: penerbit' in D:\zend\Apache2\htdocs\Ta_Web\app\storage\views\eecbfdfc468020169e683f00580865e1:30 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\app\storage\views\eecbfdfc468020169e683f00580865e1(30): Illuminate\Exception\Handler->handleError(8, 'Undefined varia...', 'D:\zend\Apache2...', 30, Array) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(9428): include('D:\zend\Apache2...') #2 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\View\Engines\CompilerEngine.php(45): Illuminate\View\Engines\PhpEngine->evaluatePath('D:\zend\Apache2...', Array) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(9314): Illuminate\View\Engines\CompilerEngine->get('D:\zend\Apache2...', Array) #4 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(9305): Illuminate\View\View->getContents() #5 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(9917): Illuminate\View\View->render() #6 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(9454): Illuminate\Http\Response->setContent(Object(Illuminate\View\View)) #7 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(5122): Symfony\Component\HttpFoundation\Response->__construct(Object(Illuminate\View\View)) #8 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(156): Illuminate\Routing\Router->prepare(Object(Illuminate\View\View), Object(Illuminate\Http\Request)) #9 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(126): Illuminate\Routing\Controllers\Controller->processResponse(Object(Illuminate\Routing\Router), 'view', Object(Illuminate\View\View)) #10 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4952): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'view', Array) #11 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #12 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8178): call_user_func_array(Object(Closure), Array) #13 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8165): Illuminate\Routing\Route->callCallable() #14 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4963): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #15 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #16 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #17 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #18 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #19 {main} [] []
[2014-07-14 16:02:03] log.ERROR: exception 'ErrorException' with message 'Undefined variable: penerbit' in D:\zend\Apache2\htdocs\Ta_Web\app\storage\views\eecbfdfc468020169e683f00580865e1:30 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\app\storage\views\eecbfdfc468020169e683f00580865e1(30): Illuminate\Exception\Handler->handleError(8, 'Undefined varia...', 'D:\zend\Apache2...', 30, Array) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(9428): include('D:\zend\Apache2...') #2 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\View\Engines\CompilerEngine.php(45): Illuminate\View\Engines\PhpEngine->evaluatePath('D:\zend\Apache2...', Array) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(9314): Illuminate\View\Engines\CompilerEngine->get('D:\zend\Apache2...', Array) #4 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(9305): Illuminate\View\View->getContents() #5 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(9917): Illuminate\View\View->render() #6 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(9454): Illuminate\Http\Response->setContent(Object(Illuminate\View\View)) #7 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(5122): Symfony\Component\HttpFoundation\Response->__construct(Object(Illuminate\View\View)) #8 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(156): Illuminate\Routing\Router->prepare(Object(Illuminate\View\View), Object(Illuminate\Http\Request)) #9 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(126): Illuminate\Routing\Controllers\Controller->processResponse(Object(Illuminate\Routing\Router), 'view', Object(Illuminate\View\View)) #10 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4952): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'view', Array) #11 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #12 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8178): call_user_func_array(Object(Closure), Array) #13 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8165): Illuminate\Routing\Route->callCallable() #14 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4963): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #15 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #16 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #17 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #18 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #19 {main} [] []
[2014-07-14 16:02:43] log.ERROR: exception 'ErrorException' with message 'Undefined variable: penerbit' in D:\zend\Apache2\htdocs\Ta_Web\app\storage\views\eecbfdfc468020169e683f00580865e1:30 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\app\storage\views\eecbfdfc468020169e683f00580865e1(30): Illuminate\Exception\Handler->handleError(8, 'Undefined varia...', 'D:\zend\Apache2...', 30, Array) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(9428): include('D:\zend\Apache2...') #2 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\View\Engines\CompilerEngine.php(45): Illuminate\View\Engines\PhpEngine->evaluatePath('D:\zend\Apache2...', Array) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(9314): Illuminate\View\Engines\CompilerEngine->get('D:\zend\Apache2...', Array) #4 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(9305): Illuminate\View\View->getContents() #5 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(9917): Illuminate\View\View->render() #6 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(9454): Illuminate\Http\Response->setContent(Object(Illuminate\View\View)) #7 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(5122): Symfony\Component\HttpFoundation\Response->__construct(Object(Illuminate\View\View)) #8 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(156): Illuminate\Routing\Router->prepare(Object(Illuminate\View\View), Object(Illuminate\Http\Request)) #9 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(126): Illuminate\Routing\Controllers\Controller->processResponse(Object(Illuminate\Routing\Router), 'view', Object(Illuminate\View\View)) #10 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4952): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'view', Array) #11 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #12 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8178): call_user_func_array(Object(Closure), Array) #13 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8165): Illuminate\Routing\Route->callCallable() #14 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4963): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #15 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #16 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #17 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #18 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #19 {main} [] []
[2014-07-14 16:03:26] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php:5129 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4974): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4962): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #5 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #6 {main} [] []
[2014-07-14 16:04:40] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php:5129 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4974): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4962): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #5 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #6 {main} [] []
[2014-07-14 17:04:28] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php:5129 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4974): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4962): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #5 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #6 {main} [] []
[2014-07-14 17:04:37] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php:5129 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4974): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4962): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #5 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #6 {main} [] []
[2014-07-14 17:10:42] log.ERROR: exception 'InvalidArgumentException' with message 'View [layout.bootstraplogin.index] not found.' in D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php:8422 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8395): Illuminate\View\FileViewFinder->findInPaths('layout.bootstra...', Array) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8495): Illuminate\View\FileViewFinder->find('layout.bootstra...') #2 D:\zend\Apache2\htdocs\Ta_Web\app\storage\views\171c0ea5a5ad851fc674cb53e3a02f6f(65): Illuminate\View\Environment->make('layout.bootstra...', Array) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(9428): include('D:\zend\Apache2...') #4 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\View\Engines\CompilerEngine.php(45): Illuminate\View\Engines\PhpEngine->evaluatePath('D:\zend\Apache2...', Array) #5 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(9314): Illuminate\View\Engines\CompilerEngine->get('D:\zend\Apache2...', Array) #6 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(9305): Illuminate\View\View->getContents() #7 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(9917): Illuminate\View\View->render() #8 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(9454): Illuminate\Http\Response->setContent(Object(Illuminate\View\View)) #9 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(5122): Symfony\Component\HttpFoundation\Response->__construct(Object(Illuminate\View\View)) #10 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(156): Illuminate\Routing\Router->prepare(Object(Illuminate\View\View), Object(Illuminate\Http\Request)) #11 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(126): Illuminate\Routing\Controllers\Controller->processResponse(Object(Illuminate\Routing\Router), 'index', Object(Illuminate\View\View)) #12 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4952): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'index', Array) #13 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #14 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8178): call_user_func_array(Object(Closure), Array) #15 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8165): Illuminate\Routing\Route->callCallable() #16 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4963): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #17 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #18 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #19 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #20 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #21 {main} [] []
[2014-07-14 17:11:56] log.ERROR: exception 'InvalidArgumentException' with message 'View [layout.bootstrapadmin.head] not found.' in D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php:8422 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8395): Illuminate\View\FileViewFinder->findInPaths('layout.bootstra...', Array) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8495): Illuminate\View\FileViewFinder->find('layout.bootstra...') #2 D:\zend\Apache2\htdocs\Ta_Web\app\storage\views\8d13d4ee0c2b5fb43c9279e489884143(3): Illuminate\View\Environment->make('layout.bootstra...', Array) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(9428): include('D:\zend\Apache2...') #4 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\View\Engines\CompilerEngine.php(45): Illuminate\View\Engines\PhpEngine->evaluatePath('D:\zend\Apache2...', Array) #5 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(9314): Illuminate\View\Engines\CompilerEngine->get('D:\zend\Apache2...', Array) #6 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(9305): Illuminate\View\View->getContents() #7 D:\zend\Apache2\htdocs\Ta_Web\app\storage\views\171c0ea5a5ad851fc674cb53e3a02f6f(65): Illuminate\View\View->render() #8 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(9428): include('D:\zend\Apache2...') #9 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\View\Engines\CompilerEngine.php(45): Illuminate\View\Engines\PhpEngine->evaluatePath('D:\zend\Apache2...', Array) #10 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(9314): Illuminate\View\Engines\CompilerEngine->get('D:\zend\Apache2...', Array) #11 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(9305): Illuminate\View\View->getContents() #12 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(9917): Illuminate\View\View->render() #13 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(9454): Illuminate\Http\Response->setContent(Object(Illuminate\View\View)) #14 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(5122): Symfony\Component\HttpFoundation\Response->__construct(Object(Illuminate\View\View)) #15 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(156): Illuminate\Routing\Router->prepare(Object(Illuminate\View\View), Object(Illuminate\Http\Request)) #16 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(126): Illuminate\Routing\Controllers\Controller->processResponse(Object(Illuminate\Routing\Router), 'index', Object(Illuminate\View\View)) #17 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4952): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'index', Array) #18 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #19 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8178): call_user_func_array(Object(Closure), Array) #20 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8165): Illuminate\Routing\Route->callCallable() #21 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4963): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #22 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #23 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #24 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #25 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #26 {main} [] []
[2014-07-14 17:12:47] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php:5129 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4974): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4962): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #5 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #6 {main} [] []
[2014-07-14 18:58:49] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php:5129 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4974): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4962): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #5 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #6 {main} [] []
[2014-07-14 18:59:03] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php:5129 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4974): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4962): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #5 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #6 {main} [] []
[2014-07-14 20:33:17] log.ERROR: exception 'ErrorException' with message 'Undefined variable: filegamabar' in D:\zend\Apache2\htdocs\Ta_Web\app\controllers\PenerbitController.php:72 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\app\controllers\PenerbitController.php(72): Illuminate\Exception\Handler->handleError(8, 'Undefined varia...', 'D:\zend\Apache2...', 72, Array) #1 [internal function]: App\Controllers\PenerbitController->Delete('91') #2 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array) #3 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('delete', Array) #4 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4952): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'delete', Array) #5 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('91') #6 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8178): call_user_func_array(Object(Closure), Array) #7 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8165): Illuminate\Routing\Route->callCallable() #8 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4963): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #9 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #10 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #11 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #12 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #13 {main} [] []
[2014-07-14 20:33:32] log.ERROR: exception 'ErrorException' with message 'Undefined variable: filegamabar' in D:\zend\Apache2\htdocs\Ta_Web\app\controllers\PenerbitController.php:72 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\app\controllers\PenerbitController.php(72): Illuminate\Exception\Handler->handleError(8, 'Undefined varia...', 'D:\zend\Apache2...', 72, Array) #1 [internal function]: App\Controllers\PenerbitController->Delete('91') #2 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array) #3 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('delete', Array) #4 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4952): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'delete', Array) #5 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('91') #6 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8178): call_user_func_array(Object(Closure), Array) #7 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8165): Illuminate\Routing\Route->callCallable() #8 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4963): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #9 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #10 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #11 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #12 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #13 {main} [] []
[2014-07-14 21:22:31] log.ERROR: exception 'PDOException' with message 'SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'gender' cannot be null' in D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Connection.php:331 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Connection.php(331): PDOStatement->execute(Array) #1 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Connection.php(521): Illuminate\Database\Connection->Illuminate\Database\{closure}(Object(Illuminate\Database\MySqlConnection), 'insert into `pe...', Array) #2 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Connection.php(332): Illuminate\Database\Connection->run('insert into `pe...', Array, Object(Closure)) #3 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Connection.php(289): Illuminate\Database\Connection->statement('insert into `pe...', Array) #4 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Query\Processors\Processor.php(30): Illuminate\Database\Connection->insert('insert into `pe...', Array) #5 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1444): Illuminate\Database\Query\Processors\Processor->processInsertGetId(Object(Illuminate\Database\Query\Builder), 'insert into `pe...', Array, 'id') #6 [internal function]: Illuminate\Database\Query\Builder->insertGetId(Array, 'id') #7 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Builder.php(786): call_user_func_array(Array, Array) #8 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(5947): Illuminate\Database\Eloquent\Builder->__call('insertGetId', Array) #9 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(5947): Illuminate\Database\Eloquent\Builder->insertGetId(Array, 'id') #10 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(5937): Illuminate\Database\Eloquent\Model->insertAndSetId(Object(Illuminate\Database\Eloquent\Builder), Array) #11 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(5896): Illuminate\Database\Eloquent\Model->performInsert(Object(Illuminate\Database\Eloquent\Builder)) #12 D:\zend\Apache2\htdocs\Ta_Web\app\controllers\PenulisController.php(44): Illuminate\Database\Eloquent\Model->save() #13 [internal function]: App\Controllers\PenulisController->prosesAdd() #14 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array) #15 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('prosesAdd', Array) #16 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4952): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'prosesAdd', Array) #17 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #18 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8178): call_user_func_array(Object(Closure), Array) #19 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8165): Illuminate\Routing\Route->callCallable() #20 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4963): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #21 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #22 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #23 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #24 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #25 {main} Next exception 'Exception' with message 'SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'gender' cannot be null (SQL: insert into `penulis` (`id`, `nama_penulis`, `gender`, `tgllahir`, `status`, `alamat`, `biografi`) values (?, ?, ?, ?, ?, ?, ?)) (Bindings: array (   0 => NULL,   1 => NULL,   2 => NULL,   3 => NULL,   4 => NULL,   5 => NULL,   6 => NULL, ))' in D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Connection.php:556 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Connection.php(529): Illuminate\Database\Connection->handleQueryException(Object(PDOException), 'insert into `pe...', Array) #1 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Connection.php(332): Illuminate\Database\Connection->run('insert into `pe...', Array, Object(Closure)) #2 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Connection.php(289): Illuminate\Database\Connection->statement('insert into `pe...', Array) #3 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Query\Processors\Processor.php(30): Illuminate\Database\Connection->insert('insert into `pe...', Array) #4 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1444): Illuminate\Database\Query\Processors\Processor->processInsertGetId(Object(Illuminate\Database\Query\Builder), 'insert into `pe...', Array, 'id') #5 [internal function]: Illuminate\Database\Query\Builder->insertGetId(Array, 'id') #6 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Builder.php(786): call_user_func_array(Array, Array) #7 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(5947): Illuminate\Database\Eloquent\Builder->__call('insertGetId', Array) #8 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(5947): Illuminate\Database\Eloquent\Builder->insertGetId(Array, 'id') #9 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(5937): Illuminate\Database\Eloquent\Model->insertAndSetId(Object(Illuminate\Database\Eloquent\Builder), Array) #10 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(5896): Illuminate\Database\Eloquent\Model->performInsert(Object(Illuminate\Database\Eloquent\Builder)) #11 D:\zend\Apache2\htdocs\Ta_Web\app\controllers\PenulisController.php(44): Illuminate\Database\Eloquent\Model->save() #12 [internal function]: App\Controllers\PenulisController->prosesAdd() #13 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array) #14 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('prosesAdd', Array) #15 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4952): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'prosesAdd', Array) #16 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #17 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8178): call_user_func_array(Object(Closure), Array) #18 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8165): Illuminate\Routing\Route->callCallable() #19 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4963): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #20 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #21 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #22 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #23 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #24 {main} [] []
[2014-07-14 21:23:51] log.ERROR: exception 'PDOException' with message 'SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect date value: '01/01/2014' for column 'tgllahir' at row 1' in D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Connection.php:331 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Connection.php(331): PDOStatement->execute(Array) #1 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Connection.php(521): Illuminate\Database\Connection->Illuminate\Database\{closure}(Object(Illuminate\Database\MySqlConnection), 'insert into `pe...', Array) #2 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Connection.php(332): Illuminate\Database\Connection->run('insert into `pe...', Array, Object(Closure)) #3 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Connection.php(289): Illuminate\Database\Connection->statement('insert into `pe...', Array) #4 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Query\Processors\Processor.php(30): Illuminate\Database\Connection->insert('insert into `pe...', Array) #5 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1444): Illuminate\Database\Query\Processors\Processor->processInsertGetId(Object(Illuminate\Database\Query\Builder), 'insert into `pe...', Array, 'id') #6 [internal function]: Illuminate\Database\Query\Builder->insertGetId(Array, 'id') #7 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Builder.php(786): call_user_func_array(Array, Array) #8 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(5947): Illuminate\Database\Eloquent\Builder->__call('insertGetId', Array) #9 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(5947): Illuminate\Database\Eloquent\Builder->insertGetId(Array, 'id') #10 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(5937): Illuminate\Database\Eloquent\Model->insertAndSetId(Object(Illuminate\Database\Eloquent\Builder), Array) #11 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(5896): Illuminate\Database\Eloquent\Model->performInsert(Object(Illuminate\Database\Eloquent\Builder)) #12 D:\zend\Apache2\htdocs\Ta_Web\app\controllers\PenulisController.php(44): Illuminate\Database\Eloquent\Model->save() #13 [internal function]: App\Controllers\PenulisController->prosesAdd() #14 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array) #15 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('prosesAdd', Array) #16 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4952): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'prosesAdd', Array) #17 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #18 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8178): call_user_func_array(Object(Closure), Array) #19 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8165): Illuminate\Routing\Route->callCallable() #20 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4963): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #21 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #22 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #23 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #24 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #25 {main} Next exception 'Exception' with message 'SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect date value: '01/01/2014' for column 'tgllahir' at row 1 (SQL: insert into `penulis` (`id`, `nama_penulis`, `gender`, `tgllahir`, `status`, `alamat`, `biografi`) values (?, ?, ?, ?, ?, ?, ?)) (Bindings: array (   0 => '21',   1 => 'test',   2 => 'Pria',   3 => '01/01/2014',   4 => 'Lajang',   5 => 'mataram',   6 => 'hgvtftg                ', ))' in D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Connection.php:556 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Connection.php(529): Illuminate\Database\Connection->handleQueryException(Object(PDOException), 'insert into `pe...', Array) #1 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Connection.php(332): Illuminate\Database\Connection->run('insert into `pe...', Array, Object(Closure)) #2 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Connection.php(289): Illuminate\Database\Connection->statement('insert into `pe...', Array) #3 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Query\Processors\Processor.php(30): Illuminate\Database\Connection->insert('insert into `pe...', Array) #4 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1444): Illuminate\Database\Query\Processors\Processor->processInsertGetId(Object(Illuminate\Database\Query\Builder), 'insert into `pe...', Array, 'id') #5 [internal function]: Illuminate\Database\Query\Builder->insertGetId(Array, 'id') #6 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Builder.php(786): call_user_func_array(Array, Array) #7 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(5947): Illuminate\Database\Eloquent\Builder->__call('insertGetId', Array) #8 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(5947): Illuminate\Database\Eloquent\Builder->insertGetId(Array, 'id') #9 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(5937): Illuminate\Database\Eloquent\Model->insertAndSetId(Object(Illuminate\Database\Eloquent\Builder), Array) #10 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(5896): Illuminate\Database\Eloquent\Model->performInsert(Object(Illuminate\Database\Eloquent\Builder)) #11 D:\zend\Apache2\htdocs\Ta_Web\app\controllers\PenulisController.php(44): Illuminate\Database\Eloquent\Model->save() #12 [internal function]: App\Controllers\PenulisController->prosesAdd() #13 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array) #14 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('prosesAdd', Array) #15 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4952): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'prosesAdd', Array) #16 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #17 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8178): call_user_func_array(Object(Closure), Array) #18 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8165): Illuminate\Routing\Route->callCallable() #19 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4963): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #20 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #21 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #22 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #23 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #24 {main} [] []
