[2014-07-12 15:09:53] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php:5129 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4974): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4962): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #5 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #6 {main} [] []
[2014-07-12 15:11:24] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php:5129 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4974): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4962): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #5 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #6 {main} [] []
[2014-07-12 15:11:52] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php:5129 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4974): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4962): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #5 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #6 {main} [] []
[2014-07-12 15:11:59] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php:5129 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4974): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4962): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #5 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #6 {main} [] []
[2014-07-12 15:12:04] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php:5129 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4974): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4962): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #5 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #6 {main} [] []
[2014-07-12 15:12:09] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php:5129 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4974): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4962): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #5 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #6 {main} [] []
[2014-07-12 15:13:02] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php:5129 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4974): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4962): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #5 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #6 {main} [] []
[2014-07-12 15:52:05] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php:5129 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4974): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4962): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #5 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #6 {main} [] []
[2014-07-12 15:52:05] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php:5129 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4974): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4962): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #5 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #6 {main} [] []
[2014-07-12 15:52:05] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php:5129 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4974): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4962): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #5 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #6 {main} [] []
[2014-07-12 15:52:06] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php:5129 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4974): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4962): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #5 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #6 {main} [] []
[2014-07-12 15:52:33] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php:5129 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4974): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4962): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #5 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #6 {main} [] []
[2014-07-12 15:52:33] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php:5129 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4974): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4962): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #5 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #6 {main} [] []
[2014-07-12 15:52:34] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php:5129 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4974): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4962): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #5 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #6 {main} [] []
[2014-07-12 15:52:39] log.ERROR: exception 'ErrorException' with message 'unlink(D:\zend\Apache2\htdocs\Ta_Web\public/): Permission denied' in D:\zend\Apache2\htdocs\Ta_Web\app\controllers\PenerbitController.php:72 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleError(2, 'unlink(D:\zend\...', 'D:\zend\Apache2...', 72, Array) #1 D:\zend\Apache2\htdocs\Ta_Web\app\controllers\PenerbitController.php(72): unlink('D:\zend\Apache2...') #2 [internal function]: App\Controllers\PenerbitController->Delete('1212') #3 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array) #4 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('delete', Array) #5 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4952): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'delete', Array) #6 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('1212') #7 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8178): call_user_func_array(Object(Closure), Array) #8 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8165): Illuminate\Routing\Route->callCallable() #9 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4963): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #10 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #11 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #12 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #13 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #14 {main} [] []
[2014-07-12 16:00:25] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php:5129 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4974): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4962): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #5 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #6 {main} [] []
[2014-07-12 16:00:25] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php:5129 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4974): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4962): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #5 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #6 {main} [] []
[2014-07-12 16:00:25] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php:5129 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4974): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4962): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #5 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #6 {main} [] []
[2014-07-12 16:00:25] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php:5129 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4974): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4962): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #5 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #6 {main} [] []
[2014-07-12 16:02:54] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php:5129 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4974): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4962): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #5 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #6 {main} [] []
[2014-07-12 16:02:54] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php:5129 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4974): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4962): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #5 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #6 {main} [] []
[2014-07-12 16:02:54] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php:5129 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4974): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4962): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #5 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #6 {main} [] []
[2014-07-12 16:02:54] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php:5129 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4974): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4962): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #5 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #6 {main} [] []
[2014-07-12 16:09:53] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php:5129 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4974): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4962): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #5 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #6 {main} [] []
[2014-07-12 16:09:54] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php:5129 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4974): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4962): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #5 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #6 {main} [] []
[2014-07-12 16:10:07] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php:5129 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4974): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4962): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #5 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #6 {main} [] []
[2014-07-12 16:10:07] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php:5129 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4974): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4962): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #5 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #6 {main} [] []
[2014-07-12 16:10:09] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php:5129 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4974): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4962): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #5 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #6 {main} [] []
[2014-07-12 16:10:10] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php:5129 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4974): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4962): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #5 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #6 {main} [] []
[2014-07-12 16:11:07] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php:5129 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4974): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4962): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #5 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #6 {main} [] []
[2014-07-12 16:11:13] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php:5129 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4974): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4962): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #5 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #6 {main} [] []
[2014-07-12 16:11:26] log.ERROR: exception 'ErrorException' with message 'Trying to get property of non-object' in D:\zend\Apache2\htdocs\Ta_Web\app\storage\views\946669186e41b56b3746ab829f138427:37 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\app\storage\views\946669186e41b56b3746ab829f138427(37): Illuminate\Exception\Handler->handleError(8, 'Trying to get p...', 'D:\zend\Apache2...', 37, Array) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(9428): include('D:\zend\Apache2...') #2 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\View\Engines\CompilerEngine.php(45): Illuminate\View\Engines\PhpEngine->evaluatePath('D:\zend\Apache2...', Array) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(9314): Illuminate\View\Engines\CompilerEngine->get('D:\zend\Apache2...', Array) #4 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(9305): Illuminate\View\View->getContents() #5 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(9917): Illuminate\View\View->render() #6 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(9454): Illuminate\Http\Response->setContent(Object(Illuminate\View\View)) #7 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(5122): Symfony\Component\HttpFoundation\Response->__construct(Object(Illuminate\View\View)) #8 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(156): Illuminate\Routing\Router->prepare(Object(Illuminate\View\View), Object(Illuminate\Http\Request)) #9 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(126): Illuminate\Routing\Controllers\Controller->processResponse(Object(Illuminate\Routing\Router), 'view', Object(Illuminate\View\View)) #10 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4952): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'view', Array) #11 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #12 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8178): call_user_func_array(Object(Closure), Array) #13 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8165): Illuminate\Routing\Route->callCallable() #14 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4963): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #15 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #16 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #17 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #18 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #19 {main} [] []
[2014-07-12 16:11:38] log.ERROR: exception 'ErrorException' with message 'Trying to get property of non-object' in D:\zend\Apache2\htdocs\Ta_Web\app\storage\views\946669186e41b56b3746ab829f138427:37 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\app\storage\views\946669186e41b56b3746ab829f138427(37): Illuminate\Exception\Handler->handleError(8, 'Trying to get p...', 'D:\zend\Apache2...', 37, Array) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(9428): include('D:\zend\Apache2...') #2 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\View\Engines\CompilerEngine.php(45): Illuminate\View\Engines\PhpEngine->evaluatePath('D:\zend\Apache2...', Array) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(9314): Illuminate\View\Engines\CompilerEngine->get('D:\zend\Apache2...', Array) #4 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(9305): Illuminate\View\View->getContents() #5 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(9917): Illuminate\View\View->render() #6 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(9454): Illuminate\Http\Response->setContent(Object(Illuminate\View\View)) #7 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(5122): Symfony\Component\HttpFoundation\Response->__construct(Object(Illuminate\View\View)) #8 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(156): Illuminate\Routing\Router->prepare(Object(Illuminate\View\View), Object(Illuminate\Http\Request)) #9 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(126): Illuminate\Routing\Controllers\Controller->processResponse(Object(Illuminate\Routing\Router), 'view', Object(Illuminate\View\View)) #10 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4952): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'view', Array) #11 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #12 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8178): call_user_func_array(Object(Closure), Array) #13 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8165): Illuminate\Routing\Route->callCallable() #14 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4963): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #15 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #16 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #17 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #18 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #19 {main} [] []
[2014-07-12 16:11:56] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php:5129 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4974): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4962): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #5 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #6 {main} [] []
[2014-07-12 16:11:57] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php:5129 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4974): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4962): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #5 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #6 {main} [] []
[2014-07-12 16:12:11] log.ERROR: exception 'ErrorException' with message 'unlink(D:\zend\Apache2\htdocs\Ta_Web\public/): Permission denied' in D:\zend\Apache2\htdocs\Ta_Web\app\controllers\PenerbitController.php:72 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleError(2, 'unlink(D:\zend\...', 'D:\zend\Apache2...', 72, Array) #1 D:\zend\Apache2\htdocs\Ta_Web\app\controllers\PenerbitController.php(72): unlink('D:\zend\Apache2...') #2 [internal function]: App\Controllers\PenerbitController->Delete('1212') #3 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array) #4 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('delete', Array) #5 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4952): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'delete', Array) #6 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('1212') #7 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8178): call_user_func_array(Object(Closure), Array) #8 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8165): Illuminate\Routing\Route->callCallable() #9 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4963): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #10 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #11 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #12 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #13 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #14 {main} [] []
[2014-07-12 16:12:25] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php:5129 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4974): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4962): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #5 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #6 {main} [] []
[2014-07-12 16:12:26] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php:5129 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4974): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4962): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #5 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #6 {main} [] []
[2014-07-12 16:14:40] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php:5129 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4974): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4962): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #5 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #6 {main} [] []
[2014-07-12 16:14:48] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php:5129 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4974): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4962): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #5 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #6 {main} [] []
[2014-07-12 16:14:49] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php:5129 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4974): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4962): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #5 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #6 {main} [] []
[2014-07-12 16:15:05] log.ERROR: exception 'InvalidArgumentException' with message 'View [buku.add] not found.' in D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php:8422 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8395): Illuminate\View\FileViewFinder->findInPaths('buku.add', Array) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8495): Illuminate\View\FileViewFinder->find('buku.add') #2 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(3476): Illuminate\View\Environment->make('buku.add', Array) #3 D:\zend\Apache2\htdocs\Ta_Web\app\controllers\BukuController.php(39): Illuminate\Support\Facades\Facade::__callStatic('make', Array) #4 D:\zend\Apache2\htdocs\Ta_Web\app\controllers\BukuController.php(39): Illuminate\Support\Facades\View::make('buku.add', Array) #5 [internal function]: App\Controllers\BukuController->add() #6 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array) #7 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('add', Array) #8 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4952): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'add', Array) #9 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #10 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8178): call_user_func_array(Object(Closure), Array) #11 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8165): Illuminate\Routing\Route->callCallable() #12 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4963): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #13 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #14 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #15 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #16 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #17 {main} [] []
[2014-07-12 16:15:13] log.ERROR: exception 'InvalidArgumentException' with message 'View [buku.view] not found.' in D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php:8422 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8395): Illuminate\View\FileViewFinder->findInPaths('buku.view', Array) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8495): Illuminate\View\FileViewFinder->find('buku.view') #2 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(3476): Illuminate\View\Environment->make('buku.view', Array) #3 D:\zend\Apache2\htdocs\Ta_Web\app\controllers\BukuController.php(26): Illuminate\Support\Facades\Facade::__callStatic('make', Array) #4 D:\zend\Apache2\htdocs\Ta_Web\app\controllers\BukuController.php(26): Illuminate\Support\Facades\View::make('buku.view', Array) #5 [internal function]: App\Controllers\BukuController->view() #6 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array) #7 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('view', Array) #8 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4952): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'view', Array) #9 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #10 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8178): call_user_func_array(Object(Closure), Array) #11 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8165): Illuminate\Routing\Route->callCallable() #12 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4963): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #13 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #14 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #15 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #16 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #17 {main} [] []
[2014-07-12 16:15:36] log.ERROR: exception 'InvalidArgumentException' with message 'View [buku.view] not found.' in D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php:8422 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8395): Illuminate\View\FileViewFinder->findInPaths('buku.view', Array) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8495): Illuminate\View\FileViewFinder->find('buku.view') #2 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(3476): Illuminate\View\Environment->make('buku.view', Array) #3 D:\zend\Apache2\htdocs\Ta_Web\app\controllers\BukuController.php(26): Illuminate\Support\Facades\Facade::__callStatic('make', Array) #4 D:\zend\Apache2\htdocs\Ta_Web\app\controllers\BukuController.php(26): Illuminate\Support\Facades\View::make('buku.view', Array) #5 [internal function]: App\Controllers\BukuController->view() #6 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array) #7 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('view', Array) #8 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4952): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'view', Array) #9 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #10 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8178): call_user_func_array(Object(Closure), Array) #11 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8165): Illuminate\Routing\Route->callCallable() #12 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4963): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #13 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #14 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #15 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #16 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #17 {main} [] []
[2014-07-12 16:15:52] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php:5129 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4974): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4962): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #5 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #6 {main} [] []
[2014-07-12 16:15:59] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php:5129 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4974): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4962): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #5 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #6 {main} [] []
[2014-07-12 16:16:00] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php:5129 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4974): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4962): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #5 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #6 {main} [] []
[2014-07-12 16:16:59] log.ERROR: exception 'InvalidArgumentException' with message 'View [buku.view] not found.' in D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php:8422 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8395): Illuminate\View\FileViewFinder->findInPaths('buku.view', Array) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8495): Illuminate\View\FileViewFinder->find('buku.view') #2 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(3476): Illuminate\View\Environment->make('buku.view', Array) #3 D:\zend\Apache2\htdocs\Ta_Web\app\controllers\BukuController.php(26): Illuminate\Support\Facades\Facade::__callStatic('make', Array) #4 D:\zend\Apache2\htdocs\Ta_Web\app\controllers\BukuController.php(26): Illuminate\Support\Facades\View::make('buku.view', Array) #5 [internal function]: App\Controllers\BukuController->view() #6 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array) #7 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('view', Array) #8 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4952): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'view', Array) #9 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #10 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8178): call_user_func_array(Object(Closure), Array) #11 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8165): Illuminate\Routing\Route->callCallable() #12 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4963): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #13 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #14 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #15 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #16 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #17 {main} [] []
[2014-07-12 16:18:16] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php:5129 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4974): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4962): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #5 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #6 {main} [] []
[2014-07-12 16:18:22] log.ERROR: exception 'InvalidArgumentException' with message 'View [buku.view] not found.' in D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php:8422 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8395): Illuminate\View\FileViewFinder->findInPaths('buku.view', Array) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8495): Illuminate\View\FileViewFinder->find('buku.view') #2 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(3476): Illuminate\View\Environment->make('buku.view', Array) #3 D:\zend\Apache2\htdocs\Ta_Web\app\controllers\BukuController.php(26): Illuminate\Support\Facades\Facade::__callStatic('make', Array) #4 D:\zend\Apache2\htdocs\Ta_Web\app\controllers\BukuController.php(26): Illuminate\Support\Facades\View::make('buku.view', Array) #5 [internal function]: App\Controllers\BukuController->view() #6 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array) #7 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('view', Array) #8 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4952): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'view', Array) #9 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #10 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8178): call_user_func_array(Object(Closure), Array) #11 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8165): Illuminate\Routing\Route->callCallable() #12 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4963): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #13 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #14 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #15 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #16 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #17 {main} [] []
[2014-07-12 16:19:31] log.ERROR: exception 'InvalidArgumentException' with message 'View [buku.view] not found.' in D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php:8422 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8395): Illuminate\View\FileViewFinder->findInPaths('buku.view', Array) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8495): Illuminate\View\FileViewFinder->find('buku.view') #2 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(3476): Illuminate\View\Environment->make('buku.view', Array) #3 D:\zend\Apache2\htdocs\Ta_Web\app\controllers\BukuController.php(26): Illuminate\Support\Facades\Facade::__callStatic('make', Array) #4 D:\zend\Apache2\htdocs\Ta_Web\app\controllers\BukuController.php(26): Illuminate\Support\Facades\View::make('buku.view', Array) #5 [internal function]: App\Controllers\BukuController->view() #6 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array) #7 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('view', Array) #8 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4952): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'view', Array) #9 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #10 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8178): call_user_func_array(Object(Closure), Array) #11 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8165): Illuminate\Routing\Route->callCallable() #12 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4963): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #13 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #14 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #15 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #16 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #17 {main} [] []
[2014-07-12 16:22:02] log.ERROR: exception 'ErrorException' with message 'Trying to get property of non-object' in D:\zend\Apache2\htdocs\Ta_Web\app\storage\views\946669186e41b56b3746ab829f138427:37 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\app\storage\views\946669186e41b56b3746ab829f138427(37): Illuminate\Exception\Handler->handleError(8, 'Trying to get p...', 'D:\zend\Apache2...', 37, Array) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(9428): include('D:\zend\Apache2...') #2 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\View\Engines\CompilerEngine.php(45): Illuminate\View\Engines\PhpEngine->evaluatePath('D:\zend\Apache2...', Array) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(9314): Illuminate\View\Engines\CompilerEngine->get('D:\zend\Apache2...', Array) #4 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(9305): Illuminate\View\View->getContents() #5 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(9917): Illuminate\View\View->render() #6 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(9454): Illuminate\Http\Response->setContent(Object(Illuminate\View\View)) #7 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(5122): Symfony\Component\HttpFoundation\Response->__construct(Object(Illuminate\View\View)) #8 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(156): Illuminate\Routing\Router->prepare(Object(Illuminate\View\View), Object(Illuminate\Http\Request)) #9 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(126): Illuminate\Routing\Controllers\Controller->processResponse(Object(Illuminate\Routing\Router), 'view', Object(Illuminate\View\View)) #10 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4952): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'view', Array) #11 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #12 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8178): call_user_func_array(Object(Closure), Array) #13 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8165): Illuminate\Routing\Route->callCallable() #14 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4963): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #15 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #16 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #17 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #18 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #19 {main} [] []
[2014-07-12 16:22:14] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php:5129 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4974): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4962): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #5 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #6 {main} [] []
[2014-07-12 16:22:41] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php:5129 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4974): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4962): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #5 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #6 {main} [] []
[2014-07-12 16:22:42] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php:5129 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4974): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4962): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #5 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #6 {main} [] []
[2014-07-12 16:22:46] log.ERROR: exception 'ErrorException' with message 'Trying to get property of non-object' in D:\zend\Apache2\htdocs\Ta_Web\app\storage\views\946669186e41b56b3746ab829f138427:37 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\app\storage\views\946669186e41b56b3746ab829f138427(37): Illuminate\Exception\Handler->handleError(8, 'Trying to get p...', 'D:\zend\Apache2...', 37, Array) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(9428): include('D:\zend\Apache2...') #2 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\View\Engines\CompilerEngine.php(45): Illuminate\View\Engines\PhpEngine->evaluatePath('D:\zend\Apache2...', Array) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(9314): Illuminate\View\Engines\CompilerEngine->get('D:\zend\Apache2...', Array) #4 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(9305): Illuminate\View\View->getContents() #5 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(9917): Illuminate\View\View->render() #6 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(9454): Illuminate\Http\Response->setContent(Object(Illuminate\View\View)) #7 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(5122): Symfony\Component\HttpFoundation\Response->__construct(Object(Illuminate\View\View)) #8 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(156): Illuminate\Routing\Router->prepare(Object(Illuminate\View\View), Object(Illuminate\Http\Request)) #9 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(126): Illuminate\Routing\Controllers\Controller->processResponse(Object(Illuminate\Routing\Router), 'view', Object(Illuminate\View\View)) #10 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4952): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'view', Array) #11 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #12 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8178): call_user_func_array(Object(Closure), Array) #13 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8165): Illuminate\Routing\Route->callCallable() #14 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4963): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #15 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #16 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #17 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #18 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #19 {main} [] []
[2014-07-12 16:24:30] log.ERROR: exception 'PDOException' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'kategori' in 'field list'' in D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Connection.php:331 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Connection.php(331): PDO->prepare('insert into `bu...') #1 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Connection.php(521): Illuminate\Database\Connection->Illuminate\Database\{closure}(Object(Illuminate\Database\MySqlConnection), 'insert into `bu...', Array) #2 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Connection.php(332): Illuminate\Database\Connection->run('insert into `bu...', Array, Object(Closure)) #3 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Connection.php(289): Illuminate\Database\Connection->statement('insert into `bu...', Array) #4 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Query\Processors\Processor.php(30): Illuminate\Database\Connection->insert('insert into `bu...', Array) #5 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1444): Illuminate\Database\Query\Processors\Processor->processInsertGetId(Object(Illuminate\Database\Query\Builder), 'insert into `bu...', Array, 'id') #6 [internal function]: Illuminate\Database\Query\Builder->insertGetId(Array, 'id') #7 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Builder.php(786): call_user_func_array(Array, Array) #8 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(5947): Illuminate\Database\Eloquent\Builder->__call('insertGetId', Array) #9 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(5947): Illuminate\Database\Eloquent\Builder->insertGetId(Array, 'id') #10 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(5937): Illuminate\Database\Eloquent\Model->insertAndSetId(Object(Illuminate\Database\Eloquent\Builder), Array) #11 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(5896): Illuminate\Database\Eloquent\Model->performInsert(Object(Illuminate\Database\Eloquent\Builder)) #12 D:\zend\Apache2\htdocs\Ta_Web\app\controllers\BukuController.php(78): Illuminate\Database\Eloquent\Model->save() #13 [internal function]: App\Controllers\BukuController->addProses() #14 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array) #15 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('addProses', Array) #16 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4952): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'addProses', Array) #17 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #18 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8178): call_user_func_array(Object(Closure), Array) #19 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8165): Illuminate\Routing\Route->callCallable() #20 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4963): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #21 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #22 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #23 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #24 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #25 {main} Next exception 'Exception' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'kategori' in 'field list' (SQL: insert into `buku` (`judul_buku`, `kategori`, `deskripsi`, `harga`, `penulis_id`, `penerbit_id`, `gambar`) values (?, ?, ?, ?, ?, ?, ?)) (Bindings: array (   0 => '1',   1 => '100',   2 => 'asd',   3 => '100',   4 => '1',   5 => '2',   6 => 'images/Lighthouse.jpg', ))' in D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Connection.php:556 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Connection.php(529): Illuminate\Database\Connection->handleQueryException(Object(PDOException), 'insert into `bu...', Array) #1 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Connection.php(332): Illuminate\Database\Connection->run('insert into `bu...', Array, Object(Closure)) #2 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Connection.php(289): Illuminate\Database\Connection->statement('insert into `bu...', Array) #3 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Query\Processors\Processor.php(30): Illuminate\Database\Connection->insert('insert into `bu...', Array) #4 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1444): Illuminate\Database\Query\Processors\Processor->processInsertGetId(Object(Illuminate\Database\Query\Builder), 'insert into `bu...', Array, 'id') #5 [internal function]: Illuminate\Database\Query\Builder->insertGetId(Array, 'id') #6 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Builder.php(786): call_user_func_array(Array, Array) #7 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(5947): Illuminate\Database\Eloquent\Builder->__call('insertGetId', Array) #8 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(5947): Illuminate\Database\Eloquent\Builder->insertGetId(Array, 'id') #9 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(5937): Illuminate\Database\Eloquent\Model->insertAndSetId(Object(Illuminate\Database\Eloquent\Builder), Array) #10 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(5896): Illuminate\Database\Eloquent\Model->performInsert(Object(Illuminate\Database\Eloquent\Builder)) #11 D:\zend\Apache2\htdocs\Ta_Web\app\controllers\BukuController.php(78): Illuminate\Database\Eloquent\Model->save() #12 [internal function]: App\Controllers\BukuController->addProses() #13 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array) #14 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('addProses', Array) #15 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4952): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'addProses', Array) #16 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #17 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8178): call_user_func_array(Object(Closure), Array) #18 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8165): Illuminate\Routing\Route->callCallable() #19 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4963): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #20 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #21 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #22 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #23 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #24 {main} [] []
[2014-07-12 16:27:31] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php:5129 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4974): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4962): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #5 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #6 {main} [] []
[2014-07-12 16:27:32] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php:5129 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4974): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4962): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #5 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #6 {main} [] []
[2014-07-12 16:27:32] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php:5129 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4974): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4962): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #5 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #6 {main} [] []
[2014-07-12 16:27:32] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php:5129 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4974): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4962): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #5 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #6 {main} [] []
[2014-07-12 16:27:33] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php:5129 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4974): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4962): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #5 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #6 {main} [] []
[2014-07-12 16:27:59] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php:5129 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4974): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4962): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #5 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #6 {main} [] []
[2014-07-12 16:27:59] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php:5129 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4974): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4962): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #5 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #6 {main} [] []
[2014-07-12 16:28:00] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php:5129 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4974): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4962): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #5 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #6 {main} [] []
[2014-07-12 16:28:06] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php:5129 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4974): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4962): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #5 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #6 {main} [] []
[2014-07-12 16:28:06] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php:5129 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4974): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4962): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #5 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #6 {main} [] []
[2014-07-12 16:28:06] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php:5129 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4974): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4962): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #5 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #6 {main} [] []
[2014-07-12 16:28:07] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php:5129 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4974): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4962): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #5 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #6 {main} [] []
[2014-07-12 16:28:09] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php:5129 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4974): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4962): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #5 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #6 {main} [] []
[2014-07-12 16:28:10] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php:5129 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4974): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4962): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #5 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #6 {main} [] []
[2014-07-12 16:28:37] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php:5129 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4974): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4962): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #5 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #6 {main} [] []
[2014-07-12 16:28:38] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php:5129 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4974): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4962): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #5 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #6 {main} [] []
[2014-07-12 16:28:40] log.ERROR: exception 'ErrorException' with message 'unlink(D:\zend\Apache2\htdocs\Ta_Web\public/images/Desain Rumah Minimalis 00458b.jpg): No such file or directory' in D:\zend\Apache2\htdocs\Ta_Web\app\controllers\PenerbitController.php:72 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleError(2, 'unlink(D:\zend\...', 'D:\zend\Apache2...', 72, Array) #1 D:\zend\Apache2\htdocs\Ta_Web\app\controllers\PenerbitController.php(72): unlink('D:\zend\Apache2...') #2 [internal function]: App\Controllers\PenerbitController->Delete('1') #3 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array) #4 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('delete', Array) #5 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4952): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'delete', Array) #6 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('1') #7 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8178): call_user_func_array(Object(Closure), Array) #8 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8165): Illuminate\Routing\Route->callCallable() #9 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4963): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #10 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #11 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #12 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #13 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #14 {main} [] []
[2014-07-12 16:28:46] log.ERROR: exception 'ErrorException' with message 'unlink(D:\zend\Apache2\htdocs\Ta_Web\public/images/Desain Rumah Minimalis 00458b.jpg): No such file or directory' in D:\zend\Apache2\htdocs\Ta_Web\app\controllers\PenerbitController.php:72 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleError(2, 'unlink(D:\zend\...', 'D:\zend\Apache2...', 72, Array) #1 D:\zend\Apache2\htdocs\Ta_Web\app\controllers\PenerbitController.php(72): unlink('D:\zend\Apache2...') #2 [internal function]: App\Controllers\PenerbitController->Delete('2') #3 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array) #4 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('delete', Array) #5 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4952): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'delete', Array) #6 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('2') #7 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8178): call_user_func_array(Object(Closure), Array) #8 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8165): Illuminate\Routing\Route->callCallable() #9 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4963): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #10 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #11 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #12 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #13 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #14 {main} [] []
[2014-07-12 16:31:00] log.ERROR: exception 'PDOException' with message 'SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`perpustakaan`.`buku`, CONSTRAINT `fk_buku_penerbit` FOREIGN KEY (`penerbit_id`) REFERENCES `penerbit` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION)' in D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Connection.php:353 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Connection.php(353): PDOStatement->execute(Array) #1 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Connection.php(521): Illuminate\Database\Connection->Illuminate\Database\{closure}(Object(Illuminate\Database\MySqlConnection), 'delete from `pe...', Array) #2 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Connection.php(356): Illuminate\Database\Connection->run('delete from `pe...', Array, Object(Closure)) #3 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Connection.php(313): Illuminate\Database\Connection->affectingStatement('delete from `pe...', Array) #4 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1511): Illuminate\Database\Connection->delete('delete from `pe...', Array) #5 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Builder.php(338): Illuminate\Database\Query\Builder->delete() #6 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(5774): Illuminate\Database\Eloquent\Builder->delete() #7 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(5754): Illuminate\Database\Eloquent\Model->performDeleteOnModel() #8 D:\zend\Apache2\htdocs\Ta_Web\app\controllers\PenerbitController.php(73): Illuminate\Database\Eloquent\Model->delete() #9 [internal function]: App\Controllers\PenerbitController->Delete('1') #10 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array) #11 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('delete', Array) #12 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4952): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'delete', Array) #13 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('1') #14 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8178): call_user_func_array(Object(Closure), Array) #15 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8165): Illuminate\Routing\Route->callCallable() #16 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4963): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #17 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #18 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #19 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #20 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #21 {main} Next exception 'Exception' with message 'SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`perpustakaan`.`buku`, CONSTRAINT `fk_buku_penerbit` FOREIGN KEY (`penerbit_id`) REFERENCES `penerbit` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION) (SQL: delete from `penerbit` where `id` = ?) (Bindings: array (   0 => 1, ))' in D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Connection.php:556 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Connection.php(529): Illuminate\Database\Connection->handleQueryException(Object(PDOException), 'delete from `pe...', Array) #1 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Connection.php(356): Illuminate\Database\Connection->run('delete from `pe...', Array, Object(Closure)) #2 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Connection.php(313): Illuminate\Database\Connection->affectingStatement('delete from `pe...', Array) #3 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1511): Illuminate\Database\Connection->delete('delete from `pe...', Array) #4 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Builder.php(338): Illuminate\Database\Query\Builder->delete() #5 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(5774): Illuminate\Database\Eloquent\Builder->delete() #6 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(5754): Illuminate\Database\Eloquent\Model->performDeleteOnModel() #7 D:\zend\Apache2\htdocs\Ta_Web\app\controllers\PenerbitController.php(73): Illuminate\Database\Eloquent\Model->delete() #8 [internal function]: App\Controllers\PenerbitController->Delete('1') #9 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array) #10 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('delete', Array) #11 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4952): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'delete', Array) #12 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('1') #13 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8178): call_user_func_array(Object(Closure), Array) #14 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8165): Illuminate\Routing\Route->callCallable() #15 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4963): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #16 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #17 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #18 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #19 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #20 {main} [] []
[2014-07-12 16:31:19] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php:5129 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4974): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4962): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #5 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #6 {main} [] []
[2014-07-12 17:01:59] log.ERROR: exception 'PDOException' with message 'SQLSTATE[HY000]: General error: 1366 Incorrect integer value: 'buku' for column 'id' at row 1' in D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Connection.php:331 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Connection.php(331): PDOStatement->execute(Array) #1 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Connection.php(521): Illuminate\Database\Connection->Illuminate\Database\{closure}(Object(Illuminate\Database\MySqlConnection), 'insert into `pe...', Array) #2 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Connection.php(332): Illuminate\Database\Connection->run('insert into `pe...', Array, Object(Closure)) #3 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Connection.php(289): Illuminate\Database\Connection->statement('insert into `pe...', Array) #4 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Query\Processors\Processor.php(30): Illuminate\Database\Connection->insert('insert into `pe...', Array) #5 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1444): Illuminate\Database\Query\Processors\Processor->processInsertGetId(Object(Illuminate\Database\Query\Builder), 'insert into `pe...', Array, 'id') #6 [internal function]: Illuminate\Database\Query\Builder->insertGetId(Array, 'id') #7 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Builder.php(786): call_user_func_array(Array, Array) #8 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(5947): Illuminate\Database\Eloquent\Builder->__call('insertGetId', Array) #9 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(5947): Illuminate\Database\Eloquent\Builder->insertGetId(Array, 'id') #10 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(5937): Illuminate\Database\Eloquent\Model->insertAndSetId(Object(Illuminate\Database\Eloquent\Builder), Array) #11 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(5896): Illuminate\Database\Eloquent\Model->performInsert(Object(Illuminate\Database\Eloquent\Builder)) #12 D:\zend\Apache2\htdocs\Ta_Web\app\controllers\PenerbitController.php(59): Illuminate\Database\Eloquent\Model->save() #13 [internal function]: App\Controllers\PenerbitController->AddProses() #14 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array) #15 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('addProses', Array) #16 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4952): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'addProses', Array) #17 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #18 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8178): call_user_func_array(Object(Closure), Array) #19 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8165): Illuminate\Routing\Route->callCallable() #20 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4963): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #21 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #22 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #23 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #24 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #25 {main} Next exception 'Exception' with message 'SQLSTATE[HY000]: General error: 1366 Incorrect integer value: 'buku' for column 'id' at row 1 (SQL: insert into `penerbit` (`id`, `nama_penerbit`, `alamat`, `no_tlp`, `gambar`) values (?, ?, ?, ?, ?)) (Bindings: array (   0 => 'buku',   1 => 'dipa',   2 => 'jalan',   3 => '081',   4 => 'images/Koala.jpg', ))' in D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Connection.php:556 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Connection.php(529): Illuminate\Database\Connection->handleQueryException(Object(PDOException), 'insert into `pe...', Array) #1 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Connection.php(332): Illuminate\Database\Connection->run('insert into `pe...', Array, Object(Closure)) #2 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Connection.php(289): Illuminate\Database\Connection->statement('insert into `pe...', Array) #3 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Query\Processors\Processor.php(30): Illuminate\Database\Connection->insert('insert into `pe...', Array) #4 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1444): Illuminate\Database\Query\Processors\Processor->processInsertGetId(Object(Illuminate\Database\Query\Builder), 'insert into `pe...', Array, 'id') #5 [internal function]: Illuminate\Database\Query\Builder->insertGetId(Array, 'id') #6 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Builder.php(786): call_user_func_array(Array, Array) #7 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(5947): Illuminate\Database\Eloquent\Builder->__call('insertGetId', Array) #8 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(5947): Illuminate\Database\Eloquent\Builder->insertGetId(Array, 'id') #9 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(5937): Illuminate\Database\Eloquent\Model->insertAndSetId(Object(Illuminate\Database\Eloquent\Builder), Array) #10 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(5896): Illuminate\Database\Eloquent\Model->performInsert(Object(Illuminate\Database\Eloquent\Builder)) #11 D:\zend\Apache2\htdocs\Ta_Web\app\controllers\PenerbitController.php(59): Illuminate\Database\Eloquent\Model->save() #12 [internal function]: App\Controllers\PenerbitController->AddProses() #13 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array) #14 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('addProses', Array) #15 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4952): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'addProses', Array) #16 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #17 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8178): call_user_func_array(Object(Closure), Array) #18 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8165): Illuminate\Routing\Route->callCallable() #19 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4963): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #20 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #21 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #22 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #23 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #24 {main} [] []
[2014-07-12 17:02:10] log.ERROR: exception 'PDOException' with message 'SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1' for key 'PRIMARY'' in D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Connection.php:331 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Connection.php(331): PDOStatement->execute(Array) #1 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Connection.php(521): Illuminate\Database\Connection->Illuminate\Database\{closure}(Object(Illuminate\Database\MySqlConnection), 'insert into `pe...', Array) #2 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Connection.php(332): Illuminate\Database\Connection->run('insert into `pe...', Array, Object(Closure)) #3 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Connection.php(289): Illuminate\Database\Connection->statement('insert into `pe...', Array) #4 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Query\Processors\Processor.php(30): Illuminate\Database\Connection->insert('insert into `pe...', Array) #5 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1444): Illuminate\Database\Query\Processors\Processor->processInsertGetId(Object(Illuminate\Database\Query\Builder), 'insert into `pe...', Array, 'id') #6 [internal function]: Illuminate\Database\Query\Builder->insertGetId(Array, 'id') #7 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Builder.php(786): call_user_func_array(Array, Array) #8 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(5947): Illuminate\Database\Eloquent\Builder->__call('insertGetId', Array) #9 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(5947): Illuminate\Database\Eloquent\Builder->insertGetId(Array, 'id') #10 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(5937): Illuminate\Database\Eloquent\Model->insertAndSetId(Object(Illuminate\Database\Eloquent\Builder), Array) #11 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(5896): Illuminate\Database\Eloquent\Model->performInsert(Object(Illuminate\Database\Eloquent\Builder)) #12 D:\zend\Apache2\htdocs\Ta_Web\app\controllers\PenerbitController.php(59): Illuminate\Database\Eloquent\Model->save() #13 [internal function]: App\Controllers\PenerbitController->AddProses() #14 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array) #15 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('addProses', Array) #16 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4952): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'addProses', Array) #17 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #18 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8178): call_user_func_array(Object(Closure), Array) #19 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8165): Illuminate\Routing\Route->callCallable() #20 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4963): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #21 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #22 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #23 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #24 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #25 {main} Next exception 'Exception' with message 'SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1' for key 'PRIMARY' (SQL: insert into `penerbit` (`id`, `nama_penerbit`, `alamat`, `no_tlp`, `gambar`) values (?, ?, ?, ?, ?)) (Bindings: array (   0 => '1',   1 => 'dipa',   2 => 'jalan',   3 => '081',   4 => 'images/Koala.jpg', ))' in D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Connection.php:556 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Connection.php(529): Illuminate\Database\Connection->handleQueryException(Object(PDOException), 'insert into `pe...', Array) #1 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Connection.php(332): Illuminate\Database\Connection->run('insert into `pe...', Array, Object(Closure)) #2 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Connection.php(289): Illuminate\Database\Connection->statement('insert into `pe...', Array) #3 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Query\Processors\Processor.php(30): Illuminate\Database\Connection->insert('insert into `pe...', Array) #4 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1444): Illuminate\Database\Query\Processors\Processor->processInsertGetId(Object(Illuminate\Database\Query\Builder), 'insert into `pe...', Array, 'id') #5 [internal function]: Illuminate\Database\Query\Builder->insertGetId(Array, 'id') #6 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Builder.php(786): call_user_func_array(Array, Array) #7 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(5947): Illuminate\Database\Eloquent\Builder->__call('insertGetId', Array) #8 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(5947): Illuminate\Database\Eloquent\Builder->insertGetId(Array, 'id') #9 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(5937): Illuminate\Database\Eloquent\Model->insertAndSetId(Object(Illuminate\Database\Eloquent\Builder), Array) #10 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(5896): Illuminate\Database\Eloquent\Model->performInsert(Object(Illuminate\Database\Eloquent\Builder)) #11 D:\zend\Apache2\htdocs\Ta_Web\app\controllers\PenerbitController.php(59): Illuminate\Database\Eloquent\Model->save() #12 [internal function]: App\Controllers\PenerbitController->AddProses() #13 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array) #14 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('addProses', Array) #15 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4952): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'addProses', Array) #16 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #17 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8178): call_user_func_array(Object(Closure), Array) #18 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8165): Illuminate\Routing\Route->callCallable() #19 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4963): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #20 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #21 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #22 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #23 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #24 {main} [] []
[2014-07-12 17:03:33] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php:5129 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4974): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4962): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #5 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #6 {main} [] []
[2014-07-12 17:03:43] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php:5129 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4974): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4962): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #5 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #6 {main} [] []
[2014-07-12 17:04:50] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php:5129 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4974): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4962): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #5 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #6 {main} [] []
[2014-07-12 17:04:52] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php:5129 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4974): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4962): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #5 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #6 {main} [] []
[2014-07-12 17:35:02] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php:5129 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4974): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4962): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #5 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #6 {main} [] []
[2014-07-12 17:35:36] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php:5129 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4974): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4962): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #5 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #6 {main} [] []
[2014-07-12 17:37:00] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php:5129 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4974): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4962): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #5 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #6 {main} [] []
[2014-07-12 17:37:03] log.ERROR: exception 'ErrorException' with message 'Undefined variable: id' in D:\zend\Apache2\htdocs\Ta_Web\app\controllers\PenulisController.php:88 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\app\controllers\PenulisController.php(88): Illuminate\Exception\Handler->handleError(8, 'Undefined varia...', 'D:\zend\Apache2...', 88, Array) #1 [internal function]: App\Controllers\PenulisController->Editproses('1') #2 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array) #3 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('editProses', Array) #4 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4952): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'editProses', Array) #5 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('1') #6 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8178): call_user_func_array(Object(Closure), Array) #7 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8165): Illuminate\Routing\Route->callCallable() #8 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4963): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #9 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #10 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #11 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #12 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #13 {main} [] []
[2014-07-12 17:39:15] log.ERROR: exception 'ErrorException' with message 'Undefined variable: ket' in D:\zend\Apache2\htdocs\Ta_Web\app\controllers\PenulisController.php:88 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\app\controllers\PenulisController.php(88): Illuminate\Exception\Handler->handleError(8, 'Undefined varia...', 'D:\zend\Apache2...', 88, Array) #1 [internal function]: App\Controllers\PenulisController->Editproses('1') #2 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array) #3 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('editProses', Array) #4 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4952): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'editProses', Array) #5 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('1') #6 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8178): call_user_func_array(Object(Closure), Array) #7 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8165): Illuminate\Routing\Route->callCallable() #8 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4963): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #9 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #10 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #11 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #12 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #13 {main} [] []
[2014-07-12 17:40:51] log.ERROR: exception 'ErrorException' with message 'Undefined variable: tBuku' in D:\zend\Apache2\htdocs\Ta_Web\app\controllers\BukuController.php:156 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\app\controllers\BukuController.php(156): Illuminate\Exception\Handler->handleError(8, 'Undefined varia...', 'D:\zend\Apache2...', 156, Array) #1 [internal function]: App\Controllers\BukuController->editProses('7') #2 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array) #3 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('editProses', Array) #4 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4952): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'editProses', Array) #5 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('7') #6 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8178): call_user_func_array(Object(Closure), Array) #7 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8165): Illuminate\Routing\Route->callCallable() #8 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4963): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #9 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #10 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #11 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #12 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #13 {main} [] []
[2014-07-12 17:46:01] log.ERROR: exception 'ErrorException' with message 'Undefined index: nama_penulis' in D:\zend\Apache2\htdocs\Ta_Web\app\controllers\PenulisController.php:96 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\app\controllers\PenulisController.php(96): Illuminate\Exception\Handler->handleError(8, 'Undefined index...', 'D:\zend\Apache2...', 96, Array) #1 [internal function]: App\Controllers\PenulisController->Editproses('1') #2 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array) #3 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('editProses', Array) #4 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4952): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'editProses', Array) #5 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('1') #6 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8178): call_user_func_array(Object(Closure), Array) #7 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8165): Illuminate\Routing\Route->callCallable() #8 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4963): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #9 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #10 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #11 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #12 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #13 {main} [] []
[2014-07-12 17:46:22] log.ERROR: exception 'PDOException' with message 'SQLSTATE[01000]: Warning: 1265 Data truncated for column 'gender' at row 1' in D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Connection.php:353 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Connection.php(353): PDOStatement->execute(Array) #1 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Connection.php(521): Illuminate\Database\Connection->Illuminate\Database\{closure}(Object(Illuminate\Database\MySqlConnection), 'update `penulis...', Array) #2 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Connection.php(356): Illuminate\Database\Connection->run('update `penulis...', Array, Object(Closure)) #3 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Connection.php(301): Illuminate\Database\Connection->affectingStatement('update `penulis...', Array) #4 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1459): Illuminate\Database\Connection->update('update `penulis...', Array) #5 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Builder.php(277): Illuminate\Database\Query\Builder->update(Array) #6 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(5922): Illuminate\Database\Eloquent\Builder->update(Array) #7 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(5894): Illuminate\Database\Eloquent\Model->performUpdate(Object(Illuminate\Database\Eloquent\Builder)) #8 D:\zend\Apache2\htdocs\Ta_Web\app\controllers\PenulisController.php(102): Illuminate\Database\Eloquent\Model->save() #9 [internal function]: App\Controllers\PenulisController->Editproses('1') #10 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array) #11 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('editProses', Array) #12 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4952): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'editProses', Array) #13 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('1') #14 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8178): call_user_func_array(Object(Closure), Array) #15 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8165): Illuminate\Routing\Route->callCallable() #16 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4963): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #17 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #18 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #19 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #20 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #21 {main} Next exception 'Exception' with message 'SQLSTATE[01000]: Warning: 1265 Data truncated for column 'gender' at row 1 (SQL: update `penulis` set `id` = ?, `gender` = ?, `biografi` = ? where `id` = ?) (Bindings: array (   0 => '1',   1 => 'P',   2 => 'Lahir di Sebuah pedesaan yang sangat kumuh',   3 => 1, ))' in D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Connection.php:556 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Connection.php(529): Illuminate\Database\Connection->handleQueryException(Object(PDOException), 'update `penulis...', Array) #1 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Connection.php(356): Illuminate\Database\Connection->run('update `penulis...', Array, Object(Closure)) #2 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Connection.php(301): Illuminate\Database\Connection->affectingStatement('update `penulis...', Array) #3 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1459): Illuminate\Database\Connection->update('update `penulis...', Array) #4 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Builder.php(277): Illuminate\Database\Query\Builder->update(Array) #5 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(5922): Illuminate\Database\Eloquent\Builder->update(Array) #6 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(5894): Illuminate\Database\Eloquent\Model->performUpdate(Object(Illuminate\Database\Eloquent\Builder)) #7 D:\zend\Apache2\htdocs\Ta_Web\app\controllers\PenulisController.php(102): Illuminate\Database\Eloquent\Model->save() #8 [internal function]: App\Controllers\PenulisController->Editproses('1') #9 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array) #10 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('editProses', Array) #11 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4952): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'editProses', Array) #12 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('1') #13 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8178): call_user_func_array(Object(Closure), Array) #14 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8165): Illuminate\Routing\Route->callCallable() #15 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4963): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #16 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #17 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #18 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #19 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #20 {main} [] []
[2014-07-12 17:48:44] log.ERROR: exception 'PDOException' with message 'SQLSTATE[01000]: Warning: 1265 Data truncated for column 'gender' at row 1' in D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Connection.php:353 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Connection.php(353): PDOStatement->execute(Array) #1 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Connection.php(521): Illuminate\Database\Connection->Illuminate\Database\{closure}(Object(Illuminate\Database\MySqlConnection), 'update `penulis...', Array) #2 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Connection.php(356): Illuminate\Database\Connection->run('update `penulis...', Array, Object(Closure)) #3 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Connection.php(301): Illuminate\Database\Connection->affectingStatement('update `penulis...', Array) #4 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1459): Illuminate\Database\Connection->update('update `penulis...', Array) #5 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Builder.php(277): Illuminate\Database\Query\Builder->update(Array) #6 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(5922): Illuminate\Database\Eloquent\Builder->update(Array) #7 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(5894): Illuminate\Database\Eloquent\Model->performUpdate(Object(Illuminate\Database\Eloquent\Builder)) #8 D:\zend\Apache2\htdocs\Ta_Web\app\controllers\PenulisController.php(102): Illuminate\Database\Eloquent\Model->save() #9 [internal function]: App\Controllers\PenulisController->Editproses('5') #10 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array) #11 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('editProses', Array) #12 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4952): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'editProses', Array) #13 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('5') #14 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8178): call_user_func_array(Object(Closure), Array) #15 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8165): Illuminate\Routing\Route->callCallable() #16 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4963): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #17 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #18 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #19 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #20 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #21 {main} Next exception 'Exception' with message 'SQLSTATE[01000]: Warning: 1265 Data truncated for column 'gender' at row 1 (SQL: update `penulis` set `id` = ?, `nama_penulis` = ?, `gender` = ?, `status` = ?, `biografi` = ? where `id` = ?) (Bindings: array (   0 => '5',   1 => 'hendiawan ',   2 => 'L',   3 => 'Menikah',   4 => '              123123123123          ',   5 => 5, ))' in D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Connection.php:556 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Connection.php(529): Illuminate\Database\Connection->handleQueryException(Object(PDOException), 'update `penulis...', Array) #1 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Connection.php(356): Illuminate\Database\Connection->run('update `penulis...', Array, Object(Closure)) #2 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Connection.php(301): Illuminate\Database\Connection->affectingStatement('update `penulis...', Array) #3 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1459): Illuminate\Database\Connection->update('update `penulis...', Array) #4 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Builder.php(277): Illuminate\Database\Query\Builder->update(Array) #5 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(5922): Illuminate\Database\Eloquent\Builder->update(Array) #6 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(5894): Illuminate\Database\Eloquent\Model->performUpdate(Object(Illuminate\Database\Eloquent\Builder)) #7 D:\zend\Apache2\htdocs\Ta_Web\app\controllers\PenulisController.php(102): Illuminate\Database\Eloquent\Model->save() #8 [internal function]: App\Controllers\PenulisController->Editproses('5') #9 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array) #10 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('editProses', Array) #11 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4952): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'editProses', Array) #12 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('5') #13 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8178): call_user_func_array(Object(Closure), Array) #14 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8165): Illuminate\Routing\Route->callCallable() #15 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4963): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #16 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #17 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #18 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #19 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #20 {main} [] []
[2014-07-12 17:49:32] log.ERROR: exception 'PDOException' with message 'SQLSTATE[01000]: Warning: 1265 Data truncated for column 'gender' at row 1' in D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Connection.php:353 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Connection.php(353): PDOStatement->execute(Array) #1 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Connection.php(521): Illuminate\Database\Connection->Illuminate\Database\{closure}(Object(Illuminate\Database\MySqlConnection), 'update `penulis...', Array) #2 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Connection.php(356): Illuminate\Database\Connection->run('update `penulis...', Array, Object(Closure)) #3 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Connection.php(301): Illuminate\Database\Connection->affectingStatement('update `penulis...', Array) #4 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1459): Illuminate\Database\Connection->update('update `penulis...', Array) #5 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Builder.php(277): Illuminate\Database\Query\Builder->update(Array) #6 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(5922): Illuminate\Database\Eloquent\Builder->update(Array) #7 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(5894): Illuminate\Database\Eloquent\Model->performUpdate(Object(Illuminate\Database\Eloquent\Builder)) #8 D:\zend\Apache2\htdocs\Ta_Web\app\controllers\PenulisController.php(102): Illuminate\Database\Eloquent\Model->save() #9 [internal function]: App\Controllers\PenulisController->Editproses('5') #10 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array) #11 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('editProses', Array) #12 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4952): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'editProses', Array) #13 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('5') #14 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8178): call_user_func_array(Object(Closure), Array) #15 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8165): Illuminate\Routing\Route->callCallable() #16 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4963): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #17 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #18 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #19 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #20 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #21 {main} Next exception 'Exception' with message 'SQLSTATE[01000]: Warning: 1265 Data truncated for column 'gender' at row 1 (SQL: update `penulis` set `id` = ?, `nama_penulis` = ?, `gender` = ?, `status` = ?, `biografi` = ? where `id` = ?) (Bindings: array (   0 => '5',   1 => 'hendiawan ',   2 => 'L',   3 => 'Menikah',   4 => '              123123123123          ',   5 => 5, ))' in D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Connection.php:556 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Connection.php(529): Illuminate\Database\Connection->handleQueryException(Object(PDOException), 'update `penulis...', Array) #1 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Connection.php(356): Illuminate\Database\Connection->run('update `penulis...', Array, Object(Closure)) #2 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Connection.php(301): Illuminate\Database\Connection->affectingStatement('update `penulis...', Array) #3 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1459): Illuminate\Database\Connection->update('update `penulis...', Array) #4 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Builder.php(277): Illuminate\Database\Query\Builder->update(Array) #5 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(5922): Illuminate\Database\Eloquent\Builder->update(Array) #6 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(5894): Illuminate\Database\Eloquent\Model->performUpdate(Object(Illuminate\Database\Eloquent\Builder)) #7 D:\zend\Apache2\htdocs\Ta_Web\app\controllers\PenulisController.php(102): Illuminate\Database\Eloquent\Model->save() #8 [internal function]: App\Controllers\PenulisController->Editproses('5') #9 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array) #10 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('editProses', Array) #11 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4952): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'editProses', Array) #12 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('5') #13 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8178): call_user_func_array(Object(Closure), Array) #14 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8165): Illuminate\Routing\Route->callCallable() #15 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4963): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #16 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #17 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #18 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #19 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #20 {main} [] []
[2014-07-12 17:58:21] log.ERROR: exception 'ErrorException' with message 'Undefined variable: tBuku' in D:\zend\Apache2\htdocs\Ta_Web\app\controllers\BukuController.php:156 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\app\controllers\BukuController.php(156): Illuminate\Exception\Handler->handleError(8, 'Undefined varia...', 'D:\zend\Apache2...', 156, Array) #1 [internal function]: App\Controllers\BukuController->editProses('8') #2 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array) #3 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('editProses', Array) #4 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4952): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'editProses', Array) #5 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('8') #6 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8178): call_user_func_array(Object(Closure), Array) #7 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8165): Illuminate\Routing\Route->callCallable() #8 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4963): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #9 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #10 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #11 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #12 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #13 {main} [] []
[2014-07-12 17:59:06] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to a member function getClientOriginalName() on a non-object' in D:\zend\Apache2\htdocs\Ta_Web\app\controllers\BukuController.php:163 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2014-07-12 17:59:37] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to a member function getClientOriginalName() on a non-object' in D:\zend\Apache2\htdocs\Ta_Web\app\controllers\BukuController.php:163 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2014-07-12 18:01:44] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to a member function getClientOriginalName() on a non-object' in D:\zend\Apache2\htdocs\Ta_Web\app\controllers\BukuController.php:163 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2014-07-12 18:01:55] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to a member function getClientOriginalName() on a non-object' in D:\zend\Apache2\htdocs\Ta_Web\app\controllers\BukuController.php:163 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2014-07-12 18:02:19] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to a member function getClientOriginalName() on a non-object' in D:\zend\Apache2\htdocs\Ta_Web\app\controllers\BukuController.php:163 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2014-07-12 18:04:28] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to a member function getClientOriginalName() on a non-object' in D:\zend\Apache2\htdocs\Ta_Web\app\controllers\BukuController.php:163 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2014-07-12 18:05:50] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to a member function getClientOriginalName() on a non-object' in D:\zend\Apache2\htdocs\Ta_Web\app\controllers\BukuController.php:163 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2014-07-12 18:07:51] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to a member function getClientOriginalName() on a non-object' in D:\zend\Apache2\htdocs\Ta_Web\app\controllers\BukuController.php:163 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2014-07-12 18:11:09] log.ERROR: exception 'ErrorException' with message 'Undefined variable: kolom' in D:\zend\Apache2\htdocs\Ta_Web\app\storage\views\588ddc836bc5d4cd76c72bd9a3609960:92 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\app\storage\views\588ddc836bc5d4cd76c72bd9a3609960(92): Illuminate\Exception\Handler->handleError(8, 'Undefined varia...', 'D:\zend\Apache2...', 92, Array) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(9428): include('D:\zend\Apache2...') #2 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\View\Engines\CompilerEngine.php(45): Illuminate\View\Engines\PhpEngine->evaluatePath('D:\zend\Apache2...', Array) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(9314): Illuminate\View\Engines\CompilerEngine->get('D:\zend\Apache2...', Array) #4 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(9305): Illuminate\View\View->getContents() #5 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(9917): Illuminate\View\View->render() #6 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(9454): Illuminate\Http\Response->setContent(Object(Illuminate\View\View)) #7 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(5122): Symfony\Component\HttpFoundation\Response->__construct(Object(Illuminate\View\View)) #8 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(156): Illuminate\Routing\Router->prepare(Object(Illuminate\View\View), Object(Illuminate\Http\Request)) #9 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(126): Illuminate\Routing\Controllers\Controller->processResponse(Object(Illuminate\Routing\Router), 'edit', Object(Illuminate\View\View)) #10 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4952): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'edit', Array) #11 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('8') #12 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8178): call_user_func_array(Object(Closure), Array) #13 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8165): Illuminate\Routing\Route->callCallable() #14 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4963): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #15 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #16 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #17 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #18 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #19 {main} [] []
[2014-07-12 18:11:30] log.ERROR: exception 'ErrorException' with message 'Undefined variable: kolom' in D:\zend\Apache2\htdocs\Ta_Web\app\storage\views\588ddc836bc5d4cd76c72bd9a3609960:96 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\app\storage\views\588ddc836bc5d4cd76c72bd9a3609960(96): Illuminate\Exception\Handler->handleError(8, 'Undefined varia...', 'D:\zend\Apache2...', 96, Array) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(9428): include('D:\zend\Apache2...') #2 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\View\Engines\CompilerEngine.php(45): Illuminate\View\Engines\PhpEngine->evaluatePath('D:\zend\Apache2...', Array) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(9314): Illuminate\View\Engines\CompilerEngine->get('D:\zend\Apache2...', Array) #4 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(9305): Illuminate\View\View->getContents() #5 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(9917): Illuminate\View\View->render() #6 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(9454): Illuminate\Http\Response->setContent(Object(Illuminate\View\View)) #7 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(5122): Symfony\Component\HttpFoundation\Response->__construct(Object(Illuminate\View\View)) #8 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(156): Illuminate\Routing\Router->prepare(Object(Illuminate\View\View), Object(Illuminate\Http\Request)) #9 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(126): Illuminate\Routing\Controllers\Controller->processResponse(Object(Illuminate\Routing\Router), 'edit', Object(Illuminate\View\View)) #10 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4952): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'edit', Array) #11 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('8') #12 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8178): call_user_func_array(Object(Closure), Array) #13 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8165): Illuminate\Routing\Route->callCallable() #14 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4963): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #15 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #16 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #17 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #18 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #19 {main} [] []
[2014-07-12 18:11:49] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to a member function getClientOriginalName() on a non-object' in D:\zend\Apache2\htdocs\Ta_Web\app\controllers\BukuController.php:163 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2014-07-12 18:16:32] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to a member function getClientOriginalName() on a non-object' in D:\zend\Apache2\htdocs\Ta_Web\app\controllers\BukuController.php:163 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2014-07-12 18:17:01] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to a member function getClientOriginalName() on a non-object' in D:\zend\Apache2\htdocs\Ta_Web\app\controllers\BukuController.php:163 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2014-07-12 22:16:55] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php:5129 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4974): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4962): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #5 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #6 {main} [] []
[2014-07-12 22:41:36] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php:5129 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4974): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4962): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #5 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #6 {main} [] []
[2014-07-12 22:54:36] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php:5129 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4974): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4962): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #5 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #6 {main} [] []
[2014-07-12 22:57:04] log.ERROR: exception 'ErrorException' with message 'Undefined variable: kolom' in D:\zend\Apache2\htdocs\Ta_Web\app\controllers\LoginController.php:42 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\app\controllers\LoginController.php(42): Illuminate\Exception\Handler->handleError(8, 'Undefined varia...', 'D:\zend\Apache2...', 42, Array) #1 [internal function]: App\Controllers\LoginController->ProsesLogin() #2 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array) #3 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('ProsesLogin', Array) #4 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4952): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'ProsesLogin', Array) #5 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #6 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8178): call_user_func_array(Object(Closure), Array) #7 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8165): Illuminate\Routing\Route->callCallable() #8 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4963): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #9 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #10 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #11 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #12 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #13 {main} [] []
[2014-07-12 22:59:21] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php:5129 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4974): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4962): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #5 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #6 {main} [] []
[2014-07-12 23:11:57] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php:5129 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4974): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4962): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #5 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #6 {main} [] []
[2014-07-12 23:12:34] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php:5129 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4974): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4962): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #5 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #6 {main} [] []
[2014-07-12 23:12:45] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php:5129 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4974): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4962): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #5 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #6 {main} [] []
[2014-07-12 23:23:39] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php:5129 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4974): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4962): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #5 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #6 {main} [] []
