[2014-07-13 02:39:44] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php:5129 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4974): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4962): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #5 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #6 {main} [] []
[2014-07-13 02:40:28] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException' in D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php:5132 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4974): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\MethodNotAllowedException)) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4962): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #5 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #6 {main} [] []
[2014-07-13 02:43:10] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php:5129 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4974): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4962): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #5 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #6 {main} [] []
[2014-07-13 02:43:33] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php:5129 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4974): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4962): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #5 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #6 {main} [] []
[2014-07-13 02:43:45] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php:5129 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4974): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4962): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #5 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #6 {main} [] []
[2014-07-13 02:46:09] log.ERROR: exception 'ErrorException' with message 'Missing argument 1 for App\Controllers\PenerbitController::cari()' in D:\zend\Apache2\htdocs\Ta_Web\app\controllers\PenerbitController.php:78 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\app\controllers\PenerbitController.php(78): Illuminate\Exception\Handler->handleError(2, 'Missing argumen...', 'D:\zend\Apache2...', 78, Array) #1 [internal function]: App\Controllers\PenerbitController->cari() #2 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array) #3 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('cari', Array) #4 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4952): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'cari', Array) #5 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #6 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8178): call_user_func_array(Object(Closure), Array) #7 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8165): Illuminate\Routing\Route->callCallable() #8 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4963): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #9 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #10 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #11 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #12 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #13 {main} [] []
[2014-07-13 02:47:53] log.ERROR: exception 'ErrorException' with message 'Missing argument 1 for App\Controllers\PenerbitController::cari()' in D:\zend\Apache2\htdocs\Ta_Web\app\controllers\PenerbitController.php:78 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\app\controllers\PenerbitController.php(78): Illuminate\Exception\Handler->handleError(2, 'Missing argumen...', 'D:\zend\Apache2...', 78, Array) #1 [internal function]: App\Controllers\PenerbitController->cari() #2 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array) #3 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('cari', Array) #4 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4952): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'cari', Array) #5 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #6 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8178): call_user_func_array(Object(Closure), Array) #7 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8165): Illuminate\Routing\Route->callCallable() #8 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4963): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #9 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #10 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #11 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #12 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #13 {main} [] []
[2014-07-13 02:49:10] log.ERROR: exception 'ErrorException' with message 'Undefined index: cari' in D:\zend\Apache2\htdocs\Ta_Web\app\controllers\PenerbitController.php:84 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\app\controllers\PenerbitController.php(84): Illuminate\Exception\Handler->handleError(8, 'Undefined index...', 'D:\zend\Apache2...', 84, Array) #1 [internal function]: App\Controllers\PenerbitController->cari() #2 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array) #3 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('cari', Array) #4 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4952): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'cari', Array) #5 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #6 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8178): call_user_func_array(Object(Closure), Array) #7 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8165): Illuminate\Routing\Route->callCallable() #8 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4963): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #9 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #10 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #11 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #12 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #13 {main} [] []
[2014-07-13 02:52:34] log.ERROR: exception 'ErrorException' with message 'Undefined index: pete' in D:\zend\Apache2\htdocs\Ta_Web\app\controllers\PenerbitController.php:79 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\app\controllers\PenerbitController.php(79): Illuminate\Exception\Handler->handleError(8, 'Undefined index...', 'D:\zend\Apache2...', 79, Array) #1 [internal function]: App\Controllers\PenerbitController->cari() #2 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array) #3 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('cari', Array) #4 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4952): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'cari', Array) #5 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #6 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8178): call_user_func_array(Object(Closure), Array) #7 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8165): Illuminate\Routing\Route->callCallable() #8 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4963): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #9 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #10 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #11 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #12 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #13 {main} [] []
[2014-07-13 02:54:59] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Maximum execution time of 60 seconds exceeded' in D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Database\Connectors\Connector.php:47 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2014-07-13 03:03:33] log.ERROR: exception 'ErrorException' with message 'Undefined variable: cari' in D:\zend\Apache2\htdocs\Ta_Web\app\controllers\PenerbitController.php:88 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\app\controllers\PenerbitController.php(88): Illuminate\Exception\Handler->handleError(8, 'Undefined varia...', 'D:\zend\Apache2...', 88, Array) #1 [internal function]: App\Controllers\PenerbitController->cari() #2 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array) #3 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('cari', Array) #4 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4952): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'cari', Array) #5 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #6 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8178): call_user_func_array(Object(Closure), Array) #7 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8165): Illuminate\Routing\Route->callCallable() #8 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4963): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #9 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #10 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #11 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #12 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #13 {main} [] []
[2014-07-13 03:03:59] log.ERROR: exception 'ErrorException' with message 'Missing argument 1 for App\Controllers\PenerbitController::cari()' in D:\zend\Apache2\htdocs\Ta_Web\app\controllers\PenerbitController.php:78 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\app\controllers\PenerbitController.php(78): Illuminate\Exception\Handler->handleError(2, 'Missing argumen...', 'D:\zend\Apache2...', 78, Array) #1 [internal function]: App\Controllers\PenerbitController->cari() #2 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array) #3 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('cari', Array) #4 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4952): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'cari', Array) #5 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #6 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8178): call_user_func_array(Object(Closure), Array) #7 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8165): Illuminate\Routing\Route->callCallable() #8 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4963): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #9 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #10 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #11 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #12 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #13 {main} [] []
[2014-07-13 03:04:25] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php:5129 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4974): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4962): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #5 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #6 {main} [] []
[2014-07-13 03:05:17] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php:5129 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4974): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4962): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #5 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #6 {main} [] []
[2014-07-13 03:05:20] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php:5129 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4974): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4962): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #5 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #6 {main} [] []
[2014-07-13 03:05:57] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php:5129 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4974): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4962): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #5 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #6 {main} [] []
[2014-07-13 03:06:01] log.ERROR: exception 'ErrorException' with message 'Undefined variable: pete' in D:\zend\Apache2\htdocs\Ta_Web\app\storage\views\eecbfdfc468020169e683f00580865e1:12 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\app\storage\views\eecbfdfc468020169e683f00580865e1(12): Illuminate\Exception\Handler->handleError(8, 'Undefined varia...', 'D:\zend\Apache2...', 12, Array) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(9428): include('D:\zend\Apache2...') #2 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\View\Engines\CompilerEngine.php(45): Illuminate\View\Engines\PhpEngine->evaluatePath('D:\zend\Apache2...', Array) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(9314): Illuminate\View\Engines\CompilerEngine->get('D:\zend\Apache2...', Array) #4 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(9305): Illuminate\View\View->getContents() #5 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(9917): Illuminate\View\View->render() #6 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(9454): Illuminate\Http\Response->setContent(Object(Illuminate\View\View)) #7 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(5122): Symfony\Component\HttpFoundation\Response->__construct(Object(Illuminate\View\View)) #8 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(156): Illuminate\Routing\Router->prepare(Object(Illuminate\View\View), Object(Illuminate\Http\Request)) #9 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(126): Illuminate\Routing\Controllers\Controller->processResponse(Object(Illuminate\Routing\Router), 'view', Object(Illuminate\View\View)) #10 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4952): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'view', Array) #11 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #12 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8178): call_user_func_array(Object(Closure), Array) #13 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8165): Illuminate\Routing\Route->callCallable() #14 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4963): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #15 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #16 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #17 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #18 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #19 {main} [] []
[2014-07-13 03:06:33] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php:5129 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4974): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4962): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #5 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #6 {main} [] []
[2014-07-13 03:07:04] log.ERROR: exception 'ErrorException' with message 'Missing argument 1 for App\Controllers\PenerbitController::cari()' in D:\zend\Apache2\htdocs\Ta_Web\app\controllers\PenerbitController.php:78 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\app\controllers\PenerbitController.php(78): Illuminate\Exception\Handler->handleError(2, 'Missing argumen...', 'D:\zend\Apache2...', 78, Array) #1 [internal function]: App\Controllers\PenerbitController->cari() #2 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array) #3 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('cari', Array) #4 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4952): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'cari', Array) #5 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #6 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8178): call_user_func_array(Object(Closure), Array) #7 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8165): Illuminate\Routing\Route->callCallable() #8 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4963): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #9 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #10 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #11 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #12 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #13 {main} [] []
[2014-07-13 03:54:30] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException' in D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php:5132 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4974): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\MethodNotAllowedException)) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4962): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #5 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #6 {main} [] []
[2014-07-13 03:54:57] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException' in D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php:5132 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4974): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\MethodNotAllowedException)) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4962): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #5 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #6 {main} [] []
[2014-07-13 03:55:04] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException' in D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php:5132 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4974): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\MethodNotAllowedException)) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4962): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #5 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #6 {main} [] []
[2014-07-13 03:55:26] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException' in D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php:5132 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4974): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\MethodNotAllowedException)) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4962): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #5 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #6 {main} [] []
[2014-07-13 03:56:07] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException' in D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php:5132 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4974): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\MethodNotAllowedException)) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4962): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #5 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #6 {main} [] []
[2014-07-13 03:56:27] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException' in D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php:5132 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4974): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\MethodNotAllowedException)) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4962): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #5 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #6 {main} [] []
[2014-07-13 03:56:31] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException' in D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php:5132 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4974): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\MethodNotAllowedException)) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4962): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #5 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #6 {main} [] []
[2014-07-13 03:56:37] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException' in D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php:5132 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4974): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\MethodNotAllowedException)) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4962): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #5 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #6 {main} [] []
[2014-07-13 03:57:22] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException' in D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php:5132 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4974): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\MethodNotAllowedException)) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4962): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #5 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #6 {main} [] []
[2014-07-13 18:21:24] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php:5129 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4974): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4962): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #5 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #6 {main} [] []
[2014-07-13 18:24:17] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException' in D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php:5132 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4974): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\MethodNotAllowedException)) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4962): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #5 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #6 {main} [] []
[2014-07-13 18:25:03] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException' in D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php:5132 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4974): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\MethodNotAllowedException)) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4962): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #5 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #6 {main} [] []
[2014-07-13 18:25:13] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException' in D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php:5132 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4974): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\MethodNotAllowedException)) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4962): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #5 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #6 {main} [] []
[2014-07-13 18:26:34] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException' in D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php:5132 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4974): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\MethodNotAllowedException)) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4962): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #5 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #6 {main} [] []
[2014-07-13 18:26:40] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException' in D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php:5132 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4974): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\MethodNotAllowedException)) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4962): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #5 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #6 {main} [] []
[2014-07-13 18:26:46] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException' in D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php:5132 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4974): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\MethodNotAllowedException)) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4962): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #5 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #6 {main} [] []
[2014-07-13 18:27:07] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException' in D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php:5132 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4974): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\MethodNotAllowedException)) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4962): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #5 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #6 {main} [] []
[2014-07-13 18:50:38] log.ERROR: exception 'ErrorException' with message 'Trying to get property of non-object' in D:\zend\Apache2\htdocs\Ta_Web\app\storage\views\6cea172e687435ef61a499f5613826d3:11 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\app\storage\views\6cea172e687435ef61a499f5613826d3(11): Illuminate\Exception\Handler->handleError(8, 'Trying to get p...', 'D:\zend\Apache2...', 11, Array) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(9428): include('D:\zend\Apache2...') #2 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\View\Engines\CompilerEngine.php(45): Illuminate\View\Engines\PhpEngine->evaluatePath('D:\zend\Apache2...', Array) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(9314): Illuminate\View\Engines\CompilerEngine->get('D:\zend\Apache2...', Array) #4 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(9305): Illuminate\View\View->getContents() #5 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(9917): Illuminate\View\View->render() #6 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(9454): Illuminate\Http\Response->setContent(Object(Illuminate\View\View)) #7 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(5122): Symfony\Component\HttpFoundation\Response->__construct(Object(Illuminate\View\View)) #8 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(156): Illuminate\Routing\Router->prepare(Object(Illuminate\View\View), Object(Illuminate\Http\Request)) #9 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(126): Illuminate\Routing\Controllers\Controller->processResponse(Object(Illuminate\Routing\Router), 'Edit', Object(Illuminate\View\View)) #10 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4952): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'Edit', Array) #11 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('dipa') #12 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8178): call_user_func_array(Object(Closure), Array) #13 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8165): Illuminate\Routing\Route->callCallable() #14 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4963): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #15 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #16 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #17 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #18 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #19 {main} [] []
[2014-07-13 18:50:48] log.ERROR: exception 'ErrorException' with message 'Trying to get property of non-object' in D:\zend\Apache2\htdocs\Ta_Web\app\storage\views\6cea172e687435ef61a499f5613826d3:11 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\app\storage\views\6cea172e687435ef61a499f5613826d3(11): Illuminate\Exception\Handler->handleError(8, 'Trying to get p...', 'D:\zend\Apache2...', 11, Array) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(9428): include('D:\zend\Apache2...') #2 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\View\Engines\CompilerEngine.php(45): Illuminate\View\Engines\PhpEngine->evaluatePath('D:\zend\Apache2...', Array) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(9314): Illuminate\View\Engines\CompilerEngine->get('D:\zend\Apache2...', Array) #4 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(9305): Illuminate\View\View->getContents() #5 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(9917): Illuminate\View\View->render() #6 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(9454): Illuminate\Http\Response->setContent(Object(Illuminate\View\View)) #7 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(5122): Symfony\Component\HttpFoundation\Response->__construct(Object(Illuminate\View\View)) #8 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(156): Illuminate\Routing\Router->prepare(Object(Illuminate\View\View), Object(Illuminate\Http\Request)) #9 D:\zend\Apache2\htdocs\Ta_Web\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(126): Illuminate\Routing\Controllers\Controller->processResponse(Object(Illuminate\Routing\Router), 'Edit', Object(Illuminate\View\View)) #10 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4952): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'Edit', Array) #11 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('dipa') #12 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8178): call_user_func_array(Object(Closure), Array) #13 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(8165): Illuminate\Routing\Route->callCallable() #14 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4963): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #15 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #16 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #17 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #18 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #19 {main} [] []
[2014-07-13 22:21:15] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php:5129 Stack trace: #0 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4974): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(4962): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(534): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 D:\zend\Apache2\htdocs\Ta_Web\bootstrap\compiled.php(521): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 D:\zend\Apache2\htdocs\Ta_Web\public\index.php(49): Illuminate\Foundation\Application->run() #5 D:\zend\Apache2\htdocs\Ta_Web\server.php(19): require_once('D:\zend\Apache2...') #6 {main} [] []
